const test=require('node:test'),assert=require('node:assert/strict');
let createHandler,emailMarkup;
test.before(async()=>{({createHandler}=await import('../functions/journal-cr-send-v154/handler.mjs'));({emailMarkup}=await import('../functions/_shared/cr-email.mjs'));});
const id='aaaaaaaa-0000-4000-8000-000000000001',origin='https://ghostbuilderdev.github.io';
const request=(body={},auth=true)=>new Request('https://example.invalid/mail',{method:'POST',headers:{origin,'content-type':'application/json',...(auth?{authorization:'Bearer test'}:{})},body:JSON.stringify(body)});
function fixture(overrides={}){const calls=[],sent=[],body='CR OFF — DIFFUSION RESTREINTE\n\nChantier <test> · nuit du 2026-09-09 · v1\n\nPRODUCTION RÉALISÉE\n • Pose — 50 % réalisé\n\nITC — ZEP PRISES\n • ZEP 785\n   Prévu : 09/09 23:00 → 10/09 05:00\n   Réel : 09/09 23:05 → 10/09 04:55';
 const env={RESEND_API_KEY:'re_test_fake',JOURNAL_CR_FROM:'Journal <onboarding@resend.dev>',JOURNAL_CR_TEST_TO:'test@example.fr',...overrides};
 const rpc=async(name,args,token)=>{calls.push({name,args,token});if(name==='journal_cr_delivery_finish')return{};if(args.p_action==='email_access')return{allowed:true};if(args.p_action==='preview')return{recipients:['test@example.fr'],body,subject:'CR'};return{id,state:'pending',recipients:['test@example.fr'],body,subject:'CR'};};
 const fetcher=async(url,options)=>{sent.push({url,options});return new Response(JSON.stringify({id:'provider-id'}),{status:200});};return{env,rpc,fetcher,calls,sent,body};}
test('anonymous callers cannot check or send email',async()=>{const f=fixture(),res=await createHandler(f)(request({ids:[id]},false));assert.equal(res.status,401);assert.equal(f.calls.length,0);assert.equal(f.sent.length,0);});
test('status is authorized and never exposes API key',async()=>{const f=fixture(),r=await createHandler(f)(request({action:'status',chantier_id:id})),data=await r.json();assert.equal(data.configured,true);assert.equal(data.test_mode,true);assert.equal(f.calls[0].args.p_action,'email_access');assert.ok(!JSON.stringify(data).includes('re_test_fake'));assert.equal(f.sent.length,0);});
test('test audience is enforced before preparing any delivery',async()=>{const f=fixture({JOURNAL_CR_TEST_TO:'different@example.fr'}),res=await createHandler(f)(request({ids:[id]}));assert.equal(res.status,400);assert.equal(f.calls.length,1);assert.equal(f.calls[0].args.p_action,'preview');assert.equal(f.sent.length,0);});
test('missing test setup gives actionable error, not false success',async()=>{const f=fixture({JOURNAL_CR_TEST_TO:''}),res=await createHandler(f)(request({ids:[id]}));assert.equal(res.status,503);assert.equal(f.sent.length,0);});
test('provider receives exactly the HTML shown in preview and an idempotency key',async()=>{const f=fixture(),res=await createHandler(f)(request({ids:[id]}));assert.equal(res.status,200);assert.equal(f.sent.length,1);const {options}=f.sent[0],payload=JSON.parse(options.body);assert.equal(payload.html,emailMarkup(f.body));assert.equal(payload.text,f.body);assert.equal(options.headers['Idempotency-Key'],'journal-cr-'+id);assert.deepEqual(payload.to,['test@example.fr']);assert.match(payload.html,/<table/);assert.match(payload.html,/Chantier &lt;test&gt;/);assert.equal(f.calls.at(-1).args.p_state,'sent');});
test('a failed provider response gives a precise sender hint',async()=>{const f=fixture();f.fetcher=async()=>new Response('{}',{status:403});const res=await createHandler(f)(request({ids:[id]}));assert.equal(res.status,502);assert.match((await res.json()).error,/adresse du compte Resend/);assert.equal(f.calls.at(-1).args.p_state,'failed');});
test('a lost provider response remains uncertain and retryable',async()=>{const f=fixture();f.fetcher=async()=>{throw new Error('timeout')};const res=await createHandler(f)(request({ids:[id]}));assert.equal(res.status,502);assert.equal(f.calls.at(-1).args.p_state,'uncertain');});
