-- ONLY disposable DB: backend-fixture -> backend-production-shape ->003 ->004.
-- No network calls: configuration points at test project; pg_net absent in tests.
\set ON_ERROR_STOP on
create function public.mode_test_require(p_ok boolean,p_label text) returns boolean language plpgsql as $$
begin if p_ok is distinct from true then raise exception 'MODE TEST FAILED: %',p_label;end if;return true;end$$;
create function public.mode_test_denied(p_sql text,p_label text) returns boolean language plpgsql as $$
begin
 begin execute p_sql;exception when others then return true;end;
 raise exception 'MODE TEST UNEXPECTEDLY ALLOWED: %',p_label;
end$$;
create function public.mode_test_device(p_n int) returns uuid language sql immutable as $$select ('dddddddd-0000-4000-8000-'||lpad(p_n::text,12,'0'))::uuid$$;
create function public.mode_test_user(p_n int) returns uuid language sql immutable as $$select ('00000000-0000-4000-8000-'||lpad(p_n::text,12,'0'))::uuid$$;
create function public.mode_test_subscription(p_n int) returns jsonb language sql immutable as $$
select jsonb_build_object('endpoint','https://fcm.googleapis.com/fcm/send/mode-test-'||p_n,'keys',jsonb_build_object('p256dh',repeat('A',87),'auth',repeat('B',22)))$$;
create table public.mode_test_payload(id int primary key,value jsonb);
grant select,insert,update,delete on public.mode_test_payload to authenticated,service_role;
select public.mode_test_require(not(select enabled from journal_mode_private.config),'disabled on install');
select public.mode_test_require(not exists(select 1 from pg_constraint where connamespace='journal_mode_private'::regnamespace and confrelid in ('auth.users'::regclass,'public.profiles'::regclass)),'no new identity FK');
select public.journal_v142_assert_account_cleanup_safe();
select set_config('request.jwt.claim.sub',public.mode_test_user(2)::text,false);
set role authenticated;
select public.mode_test_require((public.journal_mode_config()->>'enabled')::boolean=false,'authenticated config disabled');
select public.mode_test_require(not(public.journal_mode_config() ? 'dispatch_secret'),'no secret in public config');
select public.mode_test_denied('select * from journal_mode_private.config','private secrets deny');
select public.mode_test_denied('select * from journal_mode_private.sessions','no cross-user table API');
select public.mode_test_denied('select public.journal_mode_dispatch_claim()','authenticated cannot dispatch');
select public.mode_test_denied($q$select public.journal_mode_start(public.mode_test_device(2),'bbbbbbbb-0000-4000-8000-000000000001',clock_timestamp()+interval '1 hour')$q$,'site B denied');
select public.mode_test_denied($q$select public.journal_mode_start(public.mode_test_device(2),'aaaaaaaa-0000-4000-8000-000000000001',clock_timestamp()+interval '25 hours')$q$,'24 hour cap');
select public.mode_test_denied($q$select public.journal_mode_start(public.mode_test_device(2),'aaaaaaaa-0000-4000-8000-000000000001',clock_timestamp()-interval '1 hour')$q$,'past end denied');
select public.mode_test_denied($q$select public.journal_mode_start(public.mode_test_device(2),'aaaaaaaa-0000-4000-8000-000000000001',clock_timestamp()+interval '1 hour',jsonb_set(public.mode_test_subscription(2),'{endpoint}','"https://127.0.0.1/push"'))$q$,'SSRF denied');
select public.mode_test_denied($q$select public.journal_mode_start(public.mode_test_device(2),'aaaaaaaa-0000-4000-8000-000000000001',clock_timestamp()+interval '1 hour',jsonb_set(public.mode_test_subscription(2),'{keys,auth}','"bad"'))$q$,'malformed subscription denied');
select public.mode_test_require(public.journal_mode_state(public.mode_test_device(99))->'session'='null'::jsonb,'unknown device no session');
reset role;
select journal_mode_private.configure(repeat('A',87),'https://testproject.supabase.co/functions/v1/journal-mode-push',repeat('S',40),true,repeat('K',43));
set role service_role;
select public.mode_test_denied('select * from journal_mode_private.config','service role cannot read secrets');
reset role;
set role anon;
select public.mode_test_denied('select public.journal_mode_config()','anonymous configuration denied');
select public.mode_test_denied('select public.journal_mode_dispatch_claim()','anonymous dispatch denied');
reset role;
set role authenticated;
insert into public.mode_test_payload values(1,public.journal_mode_start(public.mode_test_device(2),'aaaaaaaa-0000-4000-8000-000000000001',clock_timestamp()+interval '4 hours',public.mode_test_subscription(2)));
select public.mode_test_require((select(value#>>'{session,push_enabled}')::boolean from public.mode_test_payload where id=1),'push start enabled');
select public.mode_test_require((public.journal_mode_state(public.mode_test_device(2))#>>'{session,status}')='active','state active');
select public.mode_test_denied($q$select public.journal_mode_control(public.mode_test_device(2),'extend',clock_timestamp()+interval '25 hours')$q$,'extend capped');
select public.journal_mode_control(public.mode_test_device(2),'extend',clock_timestamp()+interval '5 hours');
select public.mode_test_require((public.journal_mode_state(public.mode_test_device(2))#>>'{session,ends_at}')::timestamptz>clock_timestamp()+interval '4 hours','extend works');
reset role;
-- Other users cannot see/control an existing device UUID.
select set_config('request.jwt.claim.sub',public.mode_test_user(4)::text,false);
set role authenticated;
select public.mode_test_require(public.journal_mode_state(public.mode_test_device(2))->'session'='null'::jsonb,'device scoped to owner');
select public.journal_mode_start(public.mode_test_device(4),'aaaaaaaa-0000-4000-8000-000000000001',clock_timestamp()+interval '4 hours',public.mode_test_subscription(4));
insert into public.chantier_messages(id,chantier_id,body,author_id) values('20000000-0000-4000-8000-000000000001','aaaaaaaa-0000-4000-8000-000000000001','Bonjour',public.mode_test_user(4));
reset role;
select public.mode_test_require((select count(*)=1 from journal_mode_private.queue),'own event ignored');
select public.mode_test_require((select bool_and(ready_at>clock_timestamp()+interval '10 seconds') from journal_mode_private.queue),'ordinary grouped 20sec');
set role service_role;
select public.mode_test_require(public.journal_mode_dispatch_claim()='[]'::jsonb,'ordinary not delivered immediately');
reset role;
-- Photo completes same publication even after 20sec: no extra event/queue.
update journal_mode_private.events set happened_at=clock_timestamp()-interval '30 seconds';
select set_config('request.jwt.claim.sub',public.mode_test_user(4)::text,false);
set role authenticated;
insert into public.chantier_attachments(chantier_id,message_id,storage_path,file_name)values('aaaaaaaa-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001','mode-test-photo-1','Photo.jpg');
reset role;
select public.mode_test_require((select count(*)=1 from journal_mode_private.events),'message plus late photo one event');
update journal_mode_private.queue set ready_at=clock_timestamp()-interval '1 second';
set role service_role;
insert into public.mode_test_payload values(10,public.journal_mode_dispatch_claim());
select public.mode_test_require((select jsonb_array_length(value)=1 from public.mode_test_payload where id=10),'claim one recipient');
select public.mode_test_require(public.journal_mode_dispatch_claim()='[]'::jsonb,'overlapping claim no duplicate');
insert into public.mode_test_payload values(11,public.journal_mode_dispatch_confirm((select(value->0->>'delivery_id')::uuid from public.mode_test_payload where id=10)));
select public.mode_test_require((select value is not null and value->>'event_count'='1' from public.mode_test_payload where id=11),'confirm delivery');
select public.mode_test_require(public.journal_mode_dispatch_confirm((select(value->0->>'delivery_id')::uuid from public.mode_test_payload where id=10)) is null,'confirm only once');
select public.journal_mode_dispatch_finish((select(value->0->>'delivery_id')::uuid from public.mode_test_payload where id=10),'sent');
reset role;
select public.mode_test_require((select count(*)=1 from journal_mode_private.queue where status='sent'),'finish sent');
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
-- An action without assignee must still publish (NULL priority regression).
set role authenticated;
insert into public.action_items(id,chantier_id,title,created_by)values('30000000-0000-4000-8000-000000000001','aaaaaaaa-0000-4000-8000-000000000001','Action sans pilote',public.mode_test_user(4));
insert into public.chantier_messages(id,chantier_id,body,author_id,action_id,message_type)values('20000000-0000-4000-8000-000000000002','aaaaaaaa-0000-4000-8000-000000000001','Action créée',public.mode_test_user(4),'30000000-0000-4000-8000-000000000001','Action');
reset role;
select public.mode_test_require((select count(*)=1 from journal_mode_private.events),'action plus announcement one event');
select public.mode_test_require((select count(*)=1 and bool_and(not priority) from journal_mode_private.queue),'unassigned action normal priority');
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
set role authenticated;
insert into public.action_items(id,chantier_id,title,created_by,assignee_user_id)values('30000000-0000-4000-8000-000000000002','aaaaaaaa-0000-4000-8000-000000000001','Action attribuée',public.mode_test_user(4),public.mode_test_user(2));
reset role;
select public.mode_test_require((select bool_and(priority and ready_at<=clock_timestamp()) from journal_mode_private.queue),'assignee urgent');
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
set role authenticated;
insert into public.chantier_messages(id,chantier_id,body,author_id)values('20000000-0000-4000-8000-000000000003','aaaaaaaa-0000-4000-8000-000000000001','Bonjour @Personne 2, merci',public.mode_test_user(4));
reset role;
select public.mode_test_require((select bool_and(priority) from journal_mode_private.queue),'literal full-name mention urgent');
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
set role authenticated;
insert into public.chantier_messages(id,chantier_id,body,author_id)values('20000000-0000-4000-8000-000000000004','aaaaaaaa-0000-4000-8000-000000000001','Bonjour @Personne 20',public.mode_test_user(4));
reset role;
select public.mode_test_require((select bool_and(not priority) from journal_mode_private.queue),'mention word boundary');
-- Multiple waiting events share one group; priority makes group ready now.
set role authenticated;
insert into public.chantier_messages(id,chantier_id,body,author_id,is_important)values('20000000-0000-4000-8000-000000000005','aaaaaaaa-0000-4000-8000-000000000001','Attention',public.mode_test_user(4),true);
reset role;
set role service_role;
insert into public.mode_test_payload values(20,public.journal_mode_dispatch_claim());
select public.mode_test_require((select jsonb_array_length(value)=1 and value->0->>'event_count'='2' and(value->0->>'priority')::boolean from public.mode_test_payload where id=20),'normal and urgent grouped');
reset role;
-- Presence racing after claim suppresses duplicate notification.
select set_config('request.jwt.claim.sub',public.mode_test_user(2)::text,false);
set role authenticated;
select public.journal_mode_presence(public.mode_test_device(2),true,'aaaaaaaa-0000-4000-8000-000000000001');
reset role;
set role service_role;
select public.mode_test_require(public.journal_mode_dispatch_confirm((select(value->0->>'delivery_id')::uuid from public.mode_test_payload where id=20)) is null,'presence after claim suppresses');
reset role;
select public.mode_test_require((select bool_and(status='dropped') from journal_mode_private.queue),'presence group dropped');
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
select set_config('request.jwt.claim.sub',public.mode_test_user(4)::text,false);
set role authenticated;
insert into public.chantier_messages(chantier_id,body,author_id)values('aaaaaaaa-0000-4000-8000-000000000001','Visible',public.mode_test_user(4));
reset role;
select public.mode_test_require((select bool_and(status='dropped') from journal_mode_private.queue),'visible feed no alert');
update journal_mode_private.sessions set present_until=clock_timestamp()-interval '1 second' where user_id=public.mode_test_user(2);
set role authenticated;
insert into public.chantier_messages(chantier_id,body,author_id)values('aaaaaaaa-0000-4000-8000-000000000001','Heartbeat expiré',public.mode_test_user(4));
reset role;
select public.mode_test_require((select count(*)=1 from journal_mode_private.queue where status='pending'),'presence expires server-side');
-- Pause drops outstanding events, suppresses new events, automatically resumes.
select set_config('request.jwt.claim.sub',public.mode_test_user(2)::text,false);
set role authenticated;
select public.journal_mode_control(public.mode_test_device(2),'pause',clock_timestamp()+interval '30 minutes');
select public.mode_test_require((public.journal_mode_state(public.mode_test_device(2))#>>'{session,status}')='paused','pause state');
reset role;
select public.mode_test_require((select bool_and(status='dropped') from journal_mode_private.queue),'pause drops backlog');
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
select set_config('request.jwt.claim.sub',public.mode_test_user(4)::text,false);
set role authenticated;
insert into public.chantier_messages(chantier_id,body,author_id,is_important)values('aaaaaaaa-0000-4000-8000-000000000001','Même important en pause',public.mode_test_user(4),true);
reset role;
select public.mode_test_require((select count(*)=0 from journal_mode_private.queue),'pause even urgent silent');
update journal_mode_private.sessions set pause_until=clock_timestamp()-interval '1 second' where user_id=public.mode_test_user(2);
set role authenticated;
insert into public.chantier_messages(chantier_id,body,author_id)values('aaaaaaaa-0000-4000-8000-000000000001','Après pause',public.mode_test_user(4));
reset role;
select public.mode_test_require((select count(*)=1 from journal_mode_private.queue),'auto resume new events only');
select set_config('request.jwt.claim.sub',public.mode_test_user(2)::text,false);
set role authenticated;
select public.mode_test_require((public.journal_mode_state(public.mode_test_device(2))#>>'{session,status}')='active','pause expiry state active');
select public.journal_mode_control(public.mode_test_device(2),'stop');
reset role;
select public.mode_test_require((select bool_and(status='dropped') from journal_mode_private.queue),'stop backlog dropped');
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
select set_config('request.jwt.claim.sub',public.mode_test_user(4)::text,false);
set role authenticated;
insert into public.chantier_messages(chantier_id,body,author_id,is_important)values('aaaaaaaa-0000-4000-8000-000000000001','Entre postes',public.mode_test_user(4),true);
reset role;
select public.mode_test_require((select count(*)=0 from journal_mode_private.queue),'off duty urgent silent');
select set_config('request.jwt.claim.sub',public.mode_test_user(2)::text,false);
set role authenticated;
insert into public.mode_test_payload values(30,public.journal_mode_start(public.mode_test_device(2),'aaaaaaaa-0000-4000-8000-000000000001',clock_timestamp()+interval '4 hours',public.mode_test_subscription(2)));
select public.mode_test_require((select value#>>'{recap,messages}'='1' from public.mode_test_payload where id=30),'recap between posts');
reset role;
select public.mode_test_require((select count(*)=0 from journal_mode_private.queue),'start never replays old recap');
-- Retry bounded to 3, stale confirmed lease never repeats ambiguous transport.
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
select set_config('request.jwt.claim.sub',public.mode_test_user(4)::text,false);
set role authenticated;
insert into public.chantier_messages(chantier_id,body,author_id,is_important)values('aaaaaaaa-0000-4000-8000-000000000001','Réseau',public.mode_test_user(4),true);
reset role;
set role service_role;
insert into public.mode_test_payload values(40,public.journal_mode_dispatch_claim());
select public.journal_mode_dispatch_finish((select(value->0->>'delivery_id')::uuid from public.mode_test_payload where id=40),'retry');
select public.mode_test_require(public.journal_mode_dispatch_claim()='[]'::jsonb,'retry backoff');
reset role;
update journal_mode_private.queue set ready_at=clock_timestamp()-interval '1 second',attempts=2;
set role service_role;
insert into public.mode_test_payload values(41,public.journal_mode_dispatch_claim());
select public.journal_mode_dispatch_finish((select(value->0->>'delivery_id')::uuid from public.mode_test_payload where id=41),'retry');
reset role;
select public.mode_test_require((select bool_and(status='dropped' and attempts=3) from journal_mode_private.queue),'retry bounded');
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
set role authenticated;
insert into public.chantier_messages(chantier_id,body,author_id,is_important)values('aaaaaaaa-0000-4000-8000-000000000001','Lease',public.mode_test_user(4),true);
reset role;
set role service_role;
insert into public.mode_test_payload values(42,public.journal_mode_dispatch_claim());
reset role;
update journal_mode_private.deliveries set lease_until=clock_timestamp()-interval '1 second';
set role service_role;
insert into public.mode_test_payload values(43,public.journal_mode_dispatch_claim());
select public.mode_test_require((select jsonb_array_length(value)=1 from public.mode_test_payload where id=43),'unconfirmed lease can reclaim');
select public.journal_mode_dispatch_confirm((select(value->0->>'delivery_id')::uuid from public.mode_test_payload where id=43));
reset role;
update journal_mode_private.deliveries set lease_until=clock_timestamp()-interval '1 second' where status='sending';
set role service_role;
select public.mode_test_require(public.journal_mode_dispatch_claim()='[]'::jsonb,'confirmed expired lease no duplicate');
reset role;
-- Superseded endpoint cannot send old account notifications.
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
set role authenticated;
insert into public.chantier_messages(chantier_id,body,author_id,is_important)values('aaaaaaaa-0000-4000-8000-000000000001','Téléphone partagé',public.mode_test_user(4),true);
reset role;
set role service_role;
insert into public.mode_test_payload values(50,public.journal_mode_dispatch_claim());
reset role;
set role authenticated;
select public.journal_mode_start(public.mode_test_device(2),'aaaaaaaa-0000-4000-8000-000000000001',clock_timestamp()+interval '4 hours',public.mode_test_subscription(2));
reset role;
select public.mode_test_require((select count(*)=0 from journal_mode_private.sessions where user_id=public.mode_test_user(2) and endpoint is not null),'endpoint removed from prior account');
set role service_role;
select public.mode_test_require(public.journal_mode_dispatch_confirm((select(value->0->>'delivery_id')::uuid from public.mode_test_payload where id=50)) is null,'shared phone claim invalidated');
reset role;
-- Restore user2 endpoint distinct, then test revoke between claim and confirm.
select set_config('request.jwt.claim.sub',public.mode_test_user(2)::text,false);
set role authenticated;
select public.journal_mode_start(public.mode_test_device(2),'aaaaaaaa-0000-4000-8000-000000000001',clock_timestamp()+interval '4 hours',public.mode_test_subscription(22));
reset role;
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
select set_config('request.jwt.claim.sub',public.mode_test_user(4)::text,false);
set role authenticated;
insert into public.chantier_messages(chantier_id,body,author_id,is_important)values('aaaaaaaa-0000-4000-8000-000000000001','Retrait droits',public.mode_test_user(4),true);
reset role;
set role service_role;
insert into public.mode_test_payload values(60,public.journal_mode_dispatch_claim());
reset role;
select set_config('request.jwt.claim.sub',public.mode_test_user(1)::text,false);
set role authenticated;
select public.journal_v142_revoke_user_access(public.mode_test_user(2));
reset role;
set role service_role;
select public.mode_test_require(public.journal_mode_dispatch_confirm((select(value->0->>'delivery_id')::uuid from public.mode_test_payload where id=60)) is null,'revocation after claim denied');
reset role;
select set_config('request.jwt.claim.sub',public.mode_test_user(2)::text,false);
set role authenticated;
select public.mode_test_denied('select public.journal_mode_state(public.mode_test_device(2))','revoked JWT state denied');
select public.journal_mode_forget_device(public.mode_test_device(2));
reset role;
select public.mode_test_require((select count(*)=0 from journal_mode_private.sessions where user_id=public.mode_test_user(2) and endpoint is not null),'revoked user may forget own endpoint');
-- Expiry controlled server-side, without app state call.
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
update journal_mode_private.sessions set started_at=clock_timestamp()-interval '2 hours',ends_at=clock_timestamp()-interval '1 hour' where user_id=public.mode_test_user(4);
set role service_role;
select public.mode_test_require(public.journal_mode_dispatch_claim()='[]'::jsonb,'expired session no notification');
reset role;
select public.mode_test_require((select bool_and(status='stopped' and endpoint is null) from journal_mode_private.sessions where user_id=public.mode_test_user(4)),'expired sessions stopped without client');
-- Cleanup of missing Auth UUID, deliberately no identity FK.
insert into journal_mode_private.sessions(user_id,device_id,chantier_id,started_at,ends_at,recap_since)
 values('eeeeeeee-0000-4000-8000-000000000001',public.mode_test_device(90),'aaaaaaaa-0000-4000-8000-000000000001',clock_timestamp(),clock_timestamp()+interval '1 hour',clock_timestamp());
set role service_role;
select public.journal_mode_dispatch_claim();
reset role;
select public.mode_test_require(not exists(select 1 from journal_mode_private.sessions where device_id=public.mode_test_device(90)),'orphan session cleaned');
-- Covers all feed source tables, photo-only body, metadata-only updates ignored.
select set_config('request.jwt.claim.sub',public.mode_test_user(4)::text,false);
set role authenticated;
insert into public.chantier_messages(id,chantier_id,body,author_id)values('20000000-0000-4000-8000-000000000099','aaaaaaaa-0000-4000-8000-000000000001','',public.mode_test_user(4));
insert into public.chantier_attachments(chantier_id,message_id,storage_path,file_name)values('aaaaaaaa-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000099','mode-only-photo','Photo seule.jpg');
insert into public.chantier_daily_logs(chantier_id,author_id,work_summary)values('aaaaaaaa-0000-4000-8000-000000000001',public.mode_test_user(4),'Travaux');
insert into public.chantier_risks(chantier_id,author_id,description,severity)values('aaaaaaaa-0000-4000-8000-000000000001',public.mode_test_user(4),'Risque','critique');
insert into public.chantier_documents(chantier_id,created_by,created_by_name,folder_id,storage_path,file_name)
 values('aaaaaaaa-0000-4000-8000-000000000001',public.mode_test_user(4),'Personne 4','55555555-0000-4000-8000-000000000001','mode-doc','Document.pdf');
reset role;
select public.mode_test_require((select array_agg(distinct kind order by kind)=array['document','log','message','risk'] from journal_mode_private.events),'documents logs risks photo registered');
select public.mode_test_require((select bool_and(urgent) from journal_mode_private.events where kind='risk'),'critical safety urgent');
update public.chantier_messages set author_id=null where id='20000000-0000-4000-8000-000000000099';
select public.mode_test_require((select count(*)=4 from journal_mode_private.events),'identity cleanup no event');
select public.journal_v142_assert_account_cleanup_safe();
-- Mode disabled stops all transport; internal credentials never appear public.
update journal_mode_private.config set enabled=false;
set role service_role;
select public.mode_test_require(public.journal_mode_dispatch_claim()='[]'::jsonb,'disabled transport silent');
reset role;
select set_config('request.jwt.claim.sub','',false);

-- pg_net stub records SQL-side kick decisions only, never makes a network call.
create schema net;
create table public.mode_test_net_calls(id bigint generated always as identity,url text,body jsonb,headers jsonb,timeout_ms int);
create function net.http_post(url text,body jsonb default '{}'::jsonb,params jsonb default '{}'::jsonb,headers jsonb default '{}'::jsonb,timeout_milliseconds int default 5000)
returns bigint language plpgsql as $$declare result bigint;begin
 insert into public.mode_test_net_calls(url,body,headers,timeout_ms)values(url,body,headers,timeout_milliseconds)returning id into result;return result;
end$$;
select journal_mode_private.kick();
select public.mode_test_require((select count(*)=0 from public.mode_test_net_calls),'disabled kick no Edge call');
update journal_mode_private.config set enabled=true;
select journal_mode_private.kick();
select public.mode_test_require((select count(*)=0 from public.mode_test_net_calls),'idle outside shifts no Edge call');
select set_config('request.jwt.claim.sub',public.mode_test_user(5)::text,false);
set role authenticated;
select public.journal_mode_start(public.mode_test_device(5),'aaaaaaaa-0000-4000-8000-000000000001',clock_timestamp()+interval '3 hours',public.mode_test_subscription(5));
reset role;
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
select set_config('request.jwt.claim.sub',public.mode_test_user(4)::text,false);
set role authenticated;
insert into public.chantier_messages(chantier_id,body,author_id)values('aaaaaaaa-0000-4000-8000-000000000001','Attendre groupage',public.mode_test_user(4));
reset role;
select journal_mode_private.kick();
select public.mode_test_require((select count(*)=0 from public.mode_test_net_calls),'grouping window no premature Edge call');
update journal_mode_private.queue set ready_at=clock_timestamp()-interval '1 second';
select journal_mode_private.kick();
select public.mode_test_require((select count(*)=1 and min(timeout_ms)=125000 from public.mode_test_net_calls),'ready work kicks with adequate timeout');
update journal_mode_private.queue set expires_at=clock_timestamp()-interval '1 second';
select journal_mode_private.kick();
select public.mode_test_require((select count(*)=1 from public.mode_test_net_calls),'expired work no Edge call');
select public.mode_test_require((select bool_and(status='dropped') from journal_mode_private.queue),'expired work discarded by cron');
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
set role authenticated;
insert into public.chantier_messages(chantier_id,body,author_id,is_important)values('aaaaaaaa-0000-4000-8000-000000000001','Ancien endpoint',public.mode_test_user(4),true);
reset role;
set role service_role;
insert into public.mode_test_payload values(70,public.journal_mode_dispatch_claim());
reset role;
select set_config('request.jwt.claim.sub',public.mode_test_user(5)::text,false);
set role authenticated;
select public.journal_mode_forget_device(public.mode_test_device(5));
select public.journal_mode_start(public.mode_test_device(5),'aaaaaaaa-0000-4000-8000-000000000001',clock_timestamp()+interval '3 hours',public.mode_test_subscription(55));
reset role;
set role service_role;
select public.journal_mode_dispatch_finish((select(value->0->>'delivery_id')::uuid from public.mode_test_payload where id=70),'gone');
reset role;
select public.mode_test_require((select count(*)=1 from journal_mode_private.sessions where user_id=public.mode_test_user(5) and status='active' and endpoint like '%mode-test-55'),'old gone preserves newly registered endpoint');
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
select set_config('request.jwt.claim.sub',public.mode_test_user(4)::text,false);
set role authenticated;
insert into public.chantier_messages(chantier_id,body,author_id,is_important)values('aaaaaaaa-0000-4000-8000-000000000001','Supprimer accès chantier seul',public.mode_test_user(4),true);
reset role;
set role service_role;
insert into public.mode_test_payload values(71,public.journal_mode_dispatch_claim());
reset role;
delete from public.chantier_members where user_id=public.mode_test_user(5);
set role service_role;
select public.mode_test_require(public.journal_mode_dispatch_confirm((select(value->0->>'delivery_id')::uuid from public.mode_test_payload where id=71)) is null,'site membership removed after claim suppresses');
reset role;
select set_config('request.jwt.claim.sub',public.mode_test_user(5)::text,false);
set role authenticated;
select public.mode_test_require(public.journal_mode_state(public.mode_test_device(5))->'session'='null'::jsonb,'removed site session hidden');
reset role;
select set_config('request.jwt.claim.sub','',false);

-- Capacity and fairness: >40 recipients, no UUID-order starvation.
truncate journal_mode_private.queue,journal_mode_private.deliveries,journal_mode_private.events;
insert into auth.users(id,email)select ('90000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'mode-load-'||i||'@test.invalid' from generate_series(1,55)i;
insert into public.profiles(id,full_name)select id,'Mode load '||right(id::text,2) from auth.users where id::text like '90000000-%';
insert into public.chantier_members(chantier_id,user_id,role)select 'aaaaaaaa-0000-4000-8000-000000000001',id,'lecture' from auth.users where id::text like '90000000-%';
insert into journal_mode_private.sessions(user_id,device_id,chantier_id,started_at,ends_at,recap_since,endpoint,keys)
 select id,id,'aaaaaaaa-0000-4000-8000-000000000001',clock_timestamp(),clock_timestamp()+interval '2 hours',clock_timestamp(),
 'https://fcm.googleapis.com/fcm/send/mode-load-'||id,jsonb_build_object('p256dh',repeat('A',87),'auth',repeat('B',22))
 from auth.users where id::text like '90000000-%';
select set_config('request.jwt.claim.sub',public.mode_test_user(4)::text,false);
set role authenticated;
insert into public.chantier_messages(chantier_id,body,author_id,is_important)values('aaaaaaaa-0000-4000-8000-000000000001','55 destinataires',public.mode_test_user(4),true);
reset role;
select public.mode_test_require((select count(*)=55 from journal_mode_private.queue),'55 recipient events retained');
-- Oldest waiting recipient deliberately has highest user UUID.
update journal_mode_private.queue set ready_at=clock_timestamp()-interval '1 second';
update journal_mode_private.queue q set ready_at=clock_timestamp()-interval '1 minute' from journal_mode_private.sessions s
 where s.id=q.session_id and s.user_id='90000000-0000-4000-8000-000000000055';
set role service_role;
insert into public.mode_test_payload values(80,public.journal_mode_dispatch_claim(1));
select public.mode_test_require((select value->0->>'user_id'='90000000-0000-4000-8000-000000000055' from public.mode_test_payload where id=80),'oldest queue first rather than low UUID');
insert into public.mode_test_payload values(81,public.journal_mode_dispatch_claim(40));
insert into public.mode_test_payload values(82,public.journal_mode_dispatch_claim(40));
select public.mode_test_require((select jsonb_array_length(value)=40 from public.mode_test_payload where id=81),'40 recipients claimed in one invocation');
select public.mode_test_require((select jsonb_array_length(value)=14 from public.mode_test_payload where id=82),'remaining recipients claimed without waiting for earlier leases');
select public.mode_test_require(public.journal_mode_dispatch_claim(40)='[]'::jsonb,'all 55 leased exactly once');
reset role;
select public.mode_test_require((select count(distinct session_id)=55 and count(*)=55 from journal_mode_private.deliveries where status='claimed'),'no recipient loss or duplicated delivery');
select set_config('request.jwt.claim.sub','',false);
