/* V15.5: real PDF bytes; preview renders those same bytes, never the application DOM. */
(function(root){
 'use strict';
 const viewers=new Set();let library,renderer,fontData;
 const clean=v=>String(v??'').replace(/[\u2010-\u2015]/g,'-').replace(/→/g,' > ').replace(/✓/g,'OK').replace(/•/g,'-').replace(/[\u{10000}-\u{10ffff}]/gu,'');
 async function load(){if(root.jspdf)return root.jspdf;if(!library)library=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=new URL('briefing/vendor/jspdf.umd.min.js',document.baseURI);s.onload=()=>resolve(root.jspdf);s.onerror=()=>{library=null;s.remove();reject(new Error('Le moteur PDF ne peut pas être chargé. Vérifiez la connexion et réessayez.'));};document.head.append(s);});return library;}
 async function documentPDF(title,subtitle=''){
  const {jsPDF}=await load();
  if(!fontData)fontData=Promise.all(['Regular','Bold'].map(async style=>{const r=await fetch(new URL('vendor/pdfjs/standard_fonts/LiberationSans-'+style+'.ttf',document.baseURI));if(!r.ok)throw new Error('Police PDF indisponible. Réessayez avec une connexion.');const bytes=new Uint8Array(await r.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=16384)binary+=String.fromCharCode(...bytes.subarray(i,i+16384));return btoa(binary);})).catch(e=>{fontData=null;throw e;});
  const fonts=await fontData,pdf=new jsPDF({unit:'mm',format:'a4',compress:true,putOnlyUsedFonts:true});
  fonts.forEach((data,i)=>{const name='Journal'+i+'.ttf';pdf.addFileToVFS(name,data);pdf.addFont(name,'Journal',i?'bold':'normal');});let y=20;const width=180,left=15,bottom=279;
  const room=h=>{if(y+h>bottom){pdf.addPage();y=20;}};
  const text=(value,{size=10,bold=false,color=[41,51,61],indent=0}={})=>{pdf.setFont('Journal',bold?'bold':'normal');pdf.setFontSize(size);pdf.setTextColor(...color);const lines=pdf.splitTextToSize(clean(value),width-indent);const step=size*.48;for(const line of lines){room(step);pdf.text(line,left+indent,y);y+=step;}y+=2;};
  const heading=value=>{room(17);y+=4;pdf.setDrawColor(173,18,49);pdf.line(left,y,left+width,y);y+=7;text(value,{size:13,bold:true,color:[157,16,43]});};
  const photo=(data,name)=>{const prop=pdf.getImageProperties(data),w=Math.min(width,95*prop.width/prop.height),h=w*prop.height/prop.width;room(h+13);pdf.addImage(data,'JPEG',left,y,w,h,undefined,'FAST');y+=h+5;text(name,{size:8,color:[90,101,110]});};
  const table=(heads,rows,widths)=>{const line=(values,header)=>{const cells=values.map((v,i)=>pdf.splitTextToSize(clean(v),widths[i]-6));const h=Math.max(...cells.map(c=>c.length))*4.4+5;if(y+h>bottom){pdf.addPage();y=20;if(!header)line(heads,true);}if(header){pdf.setFillColor(242,243,247);pdf.rect(left,y-4,width,h,'F');}let x=left;pdf.setFont('Journal',header?'bold':'normal');pdf.setFontSize(9);pdf.setTextColor(41,51,61);cells.forEach((c,i)=>{pdf.text(c,x+3,y);x+=widths[i];});y+=h;};line(heads,true);rows.forEach(r=>line(r,false));y+=3;};
  text('JOURNAL DE CHANTIER',{size:9,bold:true,color:[157,16,43]});text(title,{size:22,bold:true});if(subtitle)text(subtitle,{size:10});y+=3;
  return {pdf,text,heading,photo,table,finish(){const count=pdf.getNumberOfPages();for(let i=1;i<=count;i++){pdf.setPage(i);pdf.setFont('Journal','normal');pdf.setFontSize(8);pdf.setTextColor(105,111,118);pdf.text(clean(title).slice(0,90),15,290);pdf.text(`${i} / ${count}`,195,290,{align:'right'});}return pdf.output('blob');}};
 }
 async function view(blob,name,{title='Aperçu du PDF',shareLabel='Partager le document',valid=()=>true}={}){
  if(!valid())throw new Error('La session a changé.');
  const file=new File([blob],name,{type:'application/pdf'}),url=URL.createObjectURL(blob),d=document.createElement('dialog');d.className='cr-pdf-viewer';d.setAttribute('aria-label',title);
  const head=document.createElement('header');head.innerHTML='<div><small>DOCUMENT PDF</small><h2></h2></div><button class="secondary-button" data-pdf="close">Fermer ×</button>';head.querySelector('h2').textContent=title;d.append(head);
  d.insertAdjacentHTML('beforeend','<main><p role="status">Ouverture du document…</p><canvas aria-label="Page du PDF"></canvas></main><nav><button data-pdf="prev" class="secondary-button">‹</button><span data-pages></span><button data-pdf="next" class="secondary-button">›</button></nav><footer><button class="primary-button" data-pdf="share"></button><a class="secondary-button" data-pdf="download">Télécharger le PDF</a><a class="secondary-button" data-pdf="open" target="_blank" rel="noopener">Ouvrir / imprimer</a></footer>');
  d.querySelector('[data-pdf=share]').textContent=shareLabel;for(const a of d.querySelectorAll('a'))a.href=url;d.querySelector('[data-pdf=download]').download=name;
  const status=d.querySelector('[role=status]'),canvas=d.querySelector('canvas');let doc,page=1,renderTask,job,closed=false,renderSeq=0;
  const close=()=>{closed=true;renderTask?.cancel();job?.destroy();d.remove();viewers.delete(close);setTimeout(()=>URL.revokeObjectURL(url),30000);};viewers.add(close);
  const draw=async()=>{if(!doc||closed)return;const ticket=++renderSeq;renderTask?.cancel();const p=await doc.getPage(page);if(ticket!==renderSeq||closed)return;const base=p.getViewport({scale:1}),scale=Math.min(2,(d.querySelector('main').clientWidth-24)/base.width)*Math.min(devicePixelRatio||1,2),viewport=p.getViewport({scale});canvas.width=viewport.width;canvas.height=viewport.height;renderTask=p.render({canvasContext:canvas.getContext('2d'),viewport});try{await renderTask.promise;if(ticket===renderSeq){d.querySelector('[data-pages]').textContent=`Page ${page} sur ${doc.numPages}`;status.textContent='Vérifiez le document avant de le partager.';d.querySelector('[data-pdf=prev]').disabled=page===1;d.querySelector('[data-pdf=next]').disabled=page===doc.numPages;}}catch(e){if(e.name!=='RenderingCancelledException')status.textContent=e.message;}};
  d.addEventListener('cancel',e=>{e.preventDefault();close();});d.addEventListener('click',async e=>{const a=e.target.closest('[data-pdf]')?.dataset.pdf;if(a==='close')return close();if(!valid()){close();return;}if(a==='prev'||a==='next'){if(!doc)return;page=Math.max(1,Math.min(doc.numPages,page+(a==='next'?1:-1)));void draw();}if(a==='share'){try{if(navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({files:[file],title});}else status.textContent='Le partage de fichiers n’est pas proposé ici. Téléchargez le PDF, puis joignez-le depuis votre messagerie.';}catch(err){if(err.name!=='AbortError')status.textContent='Partage indisponible. Téléchargez le PDF pour le joindre à votre message.';}}});
  document.body.append(d);d.showModal();
  try{if(!renderer)renderer=import('./vendor/pdfjs/pdf.min.mjs').catch(e=>{renderer=null;throw e;});const lib=await renderer;if(closed)return;lib.GlobalWorkerOptions.workerSrc=new URL('vendor/pdfjs/pdf.worker.min.mjs',document.baseURI).href;job=lib.getDocument({data:new Uint8Array(await blob.arrayBuffer()),standardFontDataUrl:new URL('vendor/pdfjs/standard_fonts/',document.baseURI).href,isEvalSupported:false});doc=await job.promise;await draw();}catch(e){if(!closed)status.textContent='Aperçu indisponible sur cet appareil. Utilisez « Ouvrir / imprimer » ou téléchargez le PDF.';}
  return {file,close};
 }
 const stamp=v=>v?new Date(v).toLocaleString('fr-FR',{timeZone:'Europe/Paris',dateStyle:'short',timeStyle:'short'}):'Non renseigné';
 async function report(r){
  const doc=await documentPDF('CR off · '+r.chantier,`Nuit du ${r.night.split('-').reverse().join('/')} · Version ${r.revision} · ${r.state==='draft'?'BROUILLON À RELIRE':'VALIDÉ'}\nDiffusion restreinte · Horaires de Paris`);
  const labels={technique:'Production réalisée',securite:'Sécurité · tops et flops',catenaire:'Consignations caténaires',itc:'Interceptions de circulation · ITC',arf:'ARF'};
  for(const key of Object.keys(labels)){const s=r.sections.find(x=>x.key===key);if(!s)continue;doc.heading(labels[key]);if(s.status==='non_concerne'){doc.text(key==='securite'?'Rien à signaler':'Non concerné');continue;}const v=s.value||{};
   if(key==='technique'){if(v.production_mode==='text')doc.text(v.body||'À renseigner');else{const items=(v.production_sheets||[]).flatMap(p=>p.items||[]);if(items.length)for(const i of items)doc.text(`${i.additional?'Travail ajouté - ':''}${i.title} : ${i.progress==null?'avancement à confirmer':i.progress+' %'}`);doc.text(v.body||(!items.length?v.digest||'À renseigner':''));}}
   else if(key==='securite'){for(const n of s.notes||[])doc.text(`${n.category.toUpperCase()} - ${n.body}\n${n.author_name||''}`);if(!s.notes?.length)doc.text(v.digest||'À renseigner');}
   else{const rows=key==='arf'?[{label:'ARF',planned_start:v.planned_start,planned_end:v.planned_end,actual_start:v.start,actual_end:v.end,comment:v.precision}]:s.items?.filter(t=>t.active)||[];if(!rows.length)doc.text('À renseigner');for(const t of rows){doc.text(t.label+(t.track?' · Voie '+t.track:''),{bold:true});doc.table(['Horaires','Début','Fin'],[...(key==='arf'?[]:[['Prévu',stamp(t.planned_start),stamp(t.planned_end)]]),['Réel',t.status==='non_concerne'?'Non pris':stamp(t.actual_start),t.status==='non_concerne'?'Non pris':stamp(t.actual_end)]],[24,78,78]);if(t.comment)doc.text('Commentaire : '+t.comment);}}
  }
  return doc.finish();
 }
 root.JournalPDF={document:documentPDF,view,report,closeAll:()=>{for(const close of viewers)close();}};
})(window);
