(function(root){
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const format=v=>v?new Date(v).toLocaleString('fr-FR',{timeZone:'Europe/Paris'}):'';
 const imageFile=f=>(f.mime_type||f.type||'').startsWith('image/')||/\.(jpg|jpeg|png|webp|gif)$/i.test(f.file_name||f.name||'');
 const source=f=>f.signed_url||f.full_signed_url||f.data_url||f.url||'';
 const safeUrl=v=>/^(https?:|data:image\/)/i.test(v||'')?v:'';
 function select(messages,scope){return messages.filter(m=>!m.deleted_at&&(!scope.from||new Date(m.created_at)>=new Date(scope.from+'T00:00:00'))&&(!scope.to||new Date(m.created_at)<=new Date(scope.to+'T23:59:59.999'))&&(scope.scope!=='important'||JournalFeed.pinned(m)));}
 async function reducedPhoto(file,signal){
  const url=source(file);if(!url)throw new Error('Photo indisponible');
  let image=[...document.images].find(i=>i.src===url&&i.complete&&i.naturalWidth),bitmap;
  if(!image){const response=await fetch(url,{signal,credentials:'omit'});if(!response.ok)throw new Error('Photo indisponible');const blob=await response.blob();if(signal.aborted)throw new Error('Délai dépassé');bitmap=await createImageBitmap(blob);if(signal.aborted){bitmap.close();throw new Error('Délai dépassé');}image=bitmap;}
  const width=image.naturalWidth||image.width,height=image.naturalHeight||image.height,scale=Math.min(1,1000/Math.max(width,height));
  const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',.72);bitmap?.close();canvas.width=canvas.height=1;return data;
 }
 function markup({site,messages,documents=[],scope={},pilotage=''},photos){
  const attachment=f=>{const name=f.file_name||f.name||'Pièce jointe',url=safeUrl(source(f));if(imageFile(f)&&scope.photos!=='none')return photos.get(String(f.id))?`<figure><img src="${photos.get(String(f.id))}" alt="${esc(name)}"><figcaption>${esc(name)}</figcaption></figure>`:`<p class="missing">Photo indisponible : ${esc(name)}</p>`;return `<p class="file">Pièce jointe : ${url?`<a href="${esc(url)}">${esc(name)}</a>`:esc(name)}</p>`;};
  const event=m=>`<article><div class="meta">${esc(format(m.created_at))} · ${esc(m.author_name)}${m.zone?' · '+esc(m.zone):''}</div><b>${esc(m.message_type||'Information')}</b><div class="text">${esc(m.body)}</div><div class="photos">${(m.attachments||[]).map(attachment).join('')}</div></article>`;
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Journal · ${esc(site.name)}</title><style>@page{size:A4;margin:14mm}body{font:12px/1.5 Arial,sans-serif;color:#26323b;margin:24px}h1{font-size:29px;margin:10px 0}h2{font-size:17px;color:#a71232;border-bottom:2px solid #a71232;padding-bottom:8px;margin-top:26px}.cover{border-top:8px solid #a71232;padding-top:16px;margin-bottom:25px}.tag{color:#94112d;letter-spacing:1px;font-weight:bold}.meta{color:#616a72;font-size:11px;margin-bottom:6px}article{break-inside:avoid;border-top:1px solid #e0e4e6;padding:12px 0}.text{white-space:pre-wrap;overflow-wrap:anywhere}.photos{display:flex;flex-wrap:wrap;gap:12px}figure{margin:10px 0;width:46%;break-inside:avoid}figure img{width:100%;max-height:230px;object-fit:contain}figcaption{font-size:10px;color:#68717a;overflow-wrap:anywhere}.file{font-size:11px;overflow-wrap:anywhere}.missing{color:#9c1932}.complete{border-left:4px solid #238460;background:#f0f8f4;padding:10px;margin:16px 0}table{width:100%;border-collapse:collapse;font-size:11px}td,th{border-bottom:1px solid #ddd;padding:6px;text-align:left}thead{display:table-header-group}tr{break-inside:avoid}a{color:#334f60}@media print{body{margin:0}h1,h2,h3{break-after:avoid}.meta{break-after:avoid}}</style></head><body><header class="cover"><span class="tag">JOURNAL DE CHANTIER</span><h1>${esc(site.name)}</h1><p>${esc(site.lineTrack||[site.line,site.track].filter(Boolean).join(' · '))}${site.pkRange?' · PK '+esc(site.pkRange):''}${site.companies?'<br>Entreprises : '+esc(site.companies):''}</p><p>Période : ${esc(scope.from||'début du chantier')} → ${esc(scope.to||'aujourd’hui')}</p><p>${messages.length} événements · édition du ${esc(format(new Date()))}</p></header>${scope.include_pilotage?pilotage:''}${documents.length?'<h2>Registre documentaire</h2><table><thead><tr><th>Document</th><th>Classement / indice</th><th>Déposé le</th></tr></thead><tbody>'+documents.map(d=>'<tr><td>'+esc(d.file_name)+'</td><td>'+esc([d.folderLabel,d.version_label].filter(Boolean).join(' · '))+'</td><td>'+esc(format(d.created_at))+'</td></tr>').join('')+'</tbody></table>':''}<h2>Chronologie</h2>${messages.map(m=>m._completedAction?`<section class="complete"><h3>✓ Action terminée · ${esc(m._completedAction.title)}</h3><p>Clôture : ${esc(format(m.created_at))}</p>${m._history.map(event).join('')}</section>`:event(m)).join('')}</body></html>`;
 }
 function open(options){
  const messages=select(options.messages,options.scope),all=messages.flatMap(m=>m._history||[m]);const files=[...new Map(all.flatMap(m=>m.attachments||[]).filter(imageFile).map(f=>[String(f.id),f])).values()],photos=new Map();
  const d=document.createElement('dialog');d.className='production-dialog';d.innerHTML='<header><h2>Imprimer le journal</h2><button class="secondary-button" data-export="close">Fermer ×</button></header><main><div class="journal-export-status" role="status"><span></span><progress></progress></div><iframe class="journal-export-frame" title="Aperçu du carnet de chantier"></iframe></main><footer><button class="secondary-button" data-export="retry" hidden>Réessayer les photos</button><button class="primary-button" data-export="print" disabled>Préparation…</button></footer>';
  const frame=d.querySelector('iframe'),status=d.querySelector('[role=status] span'),bar=d.querySelector('progress'),print=d.querySelector('[data-export=print]'),retry=d.querySelector('[data-export=retry]');let controller,busy=false,closed=false;
  const close=()=>{closed=true;controller?.abort();d.remove();};d.addEventListener('cancel',e=>{e.preventDefault();close();});
  d.addEventListener('click',e=>{const a=e.target.closest('[data-export]')?.dataset.export;if(a==='close')close();if(a==='retry'&&!busy)void prepare();if(a==='print'&&!busy){frame.contentWindow.focus();frame.contentWindow.print();}});
  async function prepare(){
   busy=true;print.disabled=true;controller=new AbortController();let done=0,index=0;const wanted=options.scope.photos==='none'?[]:files.filter(f=>!photos.has(String(f.id)));bar.max=wanted.length||1;bar.value=0;status.textContent='Préparation du carnet…';
   const limit=setTimeout(()=>controller.abort(),15000);
   const worker=async()=>{while(index<wanted.length&&!closed){const f=wanted[index++];try{if(controller.signal.aborted)throw new Error('Délai dépassé');const signal=controller.signal;let onAbort;try{const data=await Promise.race([reducedPhoto(f,signal),new Promise((_,reject)=>{onAbort=()=>reject(new Error('Délai dépassé'));signal.addEventListener('abort',onAbort,{once:true});})]);if(!signal.aborted)photos.set(String(f.id),data);}finally{signal.removeEventListener('abort',onAbort);}}catch{}done++;bar.value=done;status.textContent=`Préparation des photos : ${done} / ${wanted.length}`;await new Promise(r=>setTimeout(r,0));}};
   await Promise.all(Array.from({length:Math.min(4,wanted.length)},worker));clearTimeout(limit);if(closed)return;
   const missing=options.scope.photos==='none'?0:files.length-photos.size;
   frame.srcdoc=markup({...options,messages},photos);
   frame.onload=async()=>{await Promise.all([...frame.contentDocument.images].map(i=>i.decode().catch(()=>{})));if(closed)return;busy=false;print.disabled=false;print.textContent=missing?`Imprimer (${missing} photo${missing>1?'s':''} indisponible${missing>1?'s':''})`:'Imprimer / enregistrer le PDF';status.textContent=missing?`${missing} photo(s) non chargée(s), signalée(s) dans le carnet. Vous pouvez réessayer avant d’imprimer.`:`Carnet prêt · ${messages.length} événements${photos.size?' · '+photos.size+' photos optimisées':''}`;retry.hidden=!missing;bar.hidden=true;};
  }
  document.body.append(d);d.showModal();void prepare();
 }
 root.JournalExport={open,select,markup};
})(window);
