/* Real V14.4 module with simulated network, worker and browser APIs. No live push claim. */
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {create,ServerClock,endFromChoice,parseRoute}=require('../mode-chantier.js');
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222';
const SITE='33333333-3333-4333-8333-333333333333',DEVICE='44444444-4444-4444-8444-444444444444';
const ID='55555555-5555-4555-8555-555555555555',BASE=Date.parse('2026-09-06T20:00:00Z');
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
const flush=()=>new Promise(resolve=>setImmediate(resolve));
function harness(options={}){
 let wall=BASE+(options.skew||0),mono=0,server=BASE,sub=null;
 const events=[],calls=[],toasts=[],storage=options.storage||new Map(),sessions=new Map();
 const context={ready:true,userId:A,currentId:SITE,chantiers:[{id:SITE,name:'Poste de nuit'}],tab:'chat'};
 const docEvents={},winEvents={},swEvents={};
 let focused=true,ack=options.ack??true;
 const doc={visibilityState:'visible',hasFocus:()=>focused,body:{classList:{toggle(){}}},getElementById:()=>null,addEventListener:(name,fn)=>docEvents[name]=fn};
 const makeSession=(user,endsAt)=>({id:ID,user_id:user,device_id:DEVICE,chantier_id:SITE,started_at:new Date(server).toISOString(),ends_at:endsAt||new Date(server+8*3600000).toISOString(),status:'active',pause_until:null,push_enabled:true});
 const response=user=>({server_now:new Date(server).toISOString(),session:sessions.get(user)||null,recap:{since:new Date(BASE-86400000).toISOString(),messages:4,actions:2,documents:1,events:0}});
 const db={async rpc(name,args){const user=context.userId;calls.push({name,args,user});if(options.rpc){const override=options.rpc({name,args,user,response,makeSession,sessions});if(override!==undefined)return override;}
 if(name==='journal_mode_config')return{data:{enabled:true,vapid_public_key:Buffer.concat([Buffer.from([4]),Buffer.alloc(64,3)]).toString('base64url'),server_now:new Date(server).toISOString()}};
 if(name==='journal_mode_state')return{data:response(user)};
 if(name==='journal_mode_start'){sessions.set(user,{...makeSession(user,args.p_ends_at),push_enabled:Boolean(args.p_subscription)});return{data:response(user)};}
 if(name==='journal_mode_control'){if(options.offline?.())throw Error('offline');const s=sessions.get(user);if(s){if(args.p_operation==='stop')s.status='stopped';if(args.p_operation==='pause'){s.status='paused';s.pause_until=args.p_until;}if(args.p_operation==='resume'){s.status='active';s.pause_until=null;}if(args.p_operation==='extend')s.ends_at=args.p_until;}return{data:response(user)};}
 if(name==='journal_mode_forget_device'){sessions.delete(user);return{data:null};}return{data:null};}};
 context.db=db;
 class Channel{constructor(){this.port1={onmessage:null,close(){}};this.port2={postMessage:data=>this.port1.onmessage?.({data})};}}
 const worker={postMessage(message,ports){events.push(message);if(ports?.length)ports[0].postMessage({ok:ack});}};
 const makeSub=()=>({endpoint:'https://fcm.googleapis.com/fcm/send/test',keys:{p256dh:'p256',auth:'auth'},toJSON(){return{endpoint:this.endpoint,keys:this.keys};},async unsubscribe(){events.push({type:'UNSUBSCRIBE',object:this});if(options.unsubscribe)return options.unsubscribe();if(sub===this)sub=null;return true;}});
 const registration={active:worker,pushManager:{getSubscription:async()=>sub,async subscribe(opts){events.push({type:'SUBSCRIBE',opts});if(options.subscribe)sub=await options.subscribe(makeSub);else sub=makeSub();return sub;}}};
 const notification={permission:options.permission||'granted',requestPermission(){events.push({type:'PERMISSION'});return options.permissionRequest?options.permissionRequest():Promise.resolve('granted');}};
 const navigator={serviceWorker:{controller:worker,ready:Promise.resolve(registration),getRegistration:async()=>registration,addEventListener:(k,v)=>swEvents[k]=v},wakeLock:{async request(){events.push({type:'WAKE'});return{async release(){events.push({type:'RELEASE'});},addEventListener(){}};}}};
 const window={document:doc,navigator,PushManager:function(){},Notification:notification,MessageChannel:Channel,atob:s=>Buffer.from(s,'base64').toString('binary'),location:{href:'https://example.com/app/'},history:{replaceState(state,title,url){events.push({type:'URL',url:String(url)});}},addEventListener:(k,v)=>winEvents[k]=v};
 const environment={window,document:options.noDocument?null:doc,navigator,deviceId:DEVICE,wallNow:()=>wall,monoNow:()=>mono,storage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},setInterval:()=>0,setTimeout:(fn,n)=>{const timer=setTimeout(fn,n);timer.unref();return timer;}};
 if(options.noDocument)window.document=null;
 const adapter={getContext:()=>context,toast:(text,tone)=>toasts.push({text,tone}),navigate:async item=>{events.push({type:'NAVIGATE',item});context.currentId=item.chantierId;context.tab='chat';return true;}};
 const mode=create(adapter,environment);
 return{mode,context,events,calls,toasts,sessions,storage,doc,environment,adapter,makeSession,response,swEvents,docEvents,winEvents,setFocused:v=>focused=v,setAck:v=>ack=v,
 advance(ms){server+=ms;wall+=ms;mono+=ms;},wallChange(ms){wall+=ms;},async init(){mode.contextChanged();await mode.restore();await mode.whenIdle();},async start(opts={}){return mode.start({chantierId:SITE,duration:'8',...opts});}};
}

test('server clock corrects initial two-day skew and survives backwards phone clock',()=>{let wall=BASE-2*86400000,mono=0;const clock=new ServerClock(()=>wall,()=>mono);clock.sync(new Date(BASE).toISOString());assert.equal(clock.now(),BASE);wall-=86400000;mono+=3600000;assert.equal(clock.now(),BASE+3600000);});
test('night shifts cross midnight; expired or >24h end rejected',()=>{assert.equal(endFromChoice('8',null,BASE),'2026-09-07T04:00:00.000Z');assert.throws(()=>endFromChoice('25',null,BASE));assert.throws(()=>endFromChoice('custom','2026-09-06T19:00:00Z',BASE));});
test('route accepts only validated local IDs and excludes injected remote URL',()=>{assert.deepEqual(parseRoute(`https://a.test/?mode=chantier&chantier=${SITE}&action=${ID}&message=https://evil.test`),{chantierId:SITE,actionId:ID,messageId:null});assert.equal(parseRoute('https://a.test/?mode=chantier&chantier=../evil'),null);});
test('real push subscription and VAPID key passed to authenticated start',async()=>{const h=harness();await h.init();await h.start();const call=h.calls.find(c=>c.name==='journal_mode_start');assert.equal(call.args.p_subscription.endpoint,'https://fcm.googleapis.com/fcm/send/test');assert.equal(h.events.find(e=>e.type==='SUBSCRIBE').opts.applicationServerKey.length,65);assert.equal(h.mode.state().recap.messages,4);assert.equal(h.mode.active(),true);assert(h.events.some(e=>e.type==='JOURNAL_MODE_STATE'&&e.state.serverNow));});
test('permission request starts synchronously in user gesture before network awaits',async()=>{const grant=deferred(),h=harness({permission:'default',permissionRequest:()=>grant.promise});await h.init();const task=h.start();assert(h.events.some(e=>e.type==='PERMISSION'));assert(!h.calls.some(c=>c.name==='journal_mode_start'));grant.resolve('granted');await task;assert(h.mode.active());});
test('denied permission still starts a clearly identified no-push session',async()=>{const h=harness({permission:'denied'});await h.init();await h.start();assert.equal(h.calls.find(c=>c.name==='journal_mode_start').args.p_subscription,null);assert(h.toasts.some(t=>t.text.includes('sans notifications')));assert(!h.events.some(e=>e.type==='SUBSCRIBE'));});
test('expires after server deadline even with wrong local clock and no network',async()=>{const h=harness({skew:-86400000});await h.init();await h.start({duration:'4'});assert.equal(h.mode.state().session.ends_at,'2026-09-07T00:00:00.000Z');h.wallChange(-86400000);h.advance(4*3600000+1);h.mode.tick();await h.mode.whenIdle();assert.equal(h.mode.active(),false);assert.equal(h.mode.state().session.status,'stopped');assert.equal(h.events.filter(e=>e.type==='JOURNAL_MODE_STATE').at(-1).state.status,'stopped');});
test('pause suppresses immediately, lasts 30min, and resume cannot extend deadline',async()=>{const h=harness();await h.init();await h.start();const end=h.mode.state().session.ends_at;await h.mode.control('pause');assert.equal(h.mode.active(),false);h.advance(30*60000+1);h.mode.tick();assert.equal(h.mode.active(),true);assert.equal(h.mode.state().session.ends_at,end);});
test('simultaneous pause/extend is serialized by busy guard before worker await',async()=>{const h=harness();await h.init();await h.start();const a=h.mode.control('pause'),b=h.mode.control('extend');await Promise.all([a,b]);assert.equal(h.calls.filter(c=>c.name==='journal_mode_control').length,1);});
test('offline stop survives process restart and active server state cannot resurrect alerts',async()=>{let offline=true;const h=harness({offline:()=>offline});await h.init();await h.start();await h.mode.control('stop');assert.equal(h.mode.active(),false);assert(h.mode.state().pending);const h2=harness({offline:()=>offline,storage:h.storage});h2.sessions.set(A,h.makeSession(A));await h2.init();assert.equal(h2.mode.active(),false);assert.equal(h2.mode.state().session.status,'stopped');assert(h2.mode.state().pending);offline=false;await h2.mode.refresh();assert.equal(h2.mode.state().pending,null);assert.equal(h2.sessions.get(A).status,'stopped');});
test('late initial restore for A cannot overwrite B session or worker identity',async()=>{const wait=deferred();let hold=true;const h=harness({rpc:({name,user,response})=>name==='journal_mode_state'&&user===A&&hold?wait.promise:undefined});h.mode.contextChanged();await flush();h.context.userId=B;h.mode.contextChanged();await h.mode.restore();h.sessions.set(B,h.makeSession(B));await h.mode.refresh();hold=false;wait.resolve({data:{server_now:new Date(BASE).toISOString(),session:h.makeSession(A)}});await flush();await h.mode.whenIdle();assert.equal(h.mode.state().userId,B);assert.equal(h.mode.state().session.user_id,B);assert.equal(h.events.filter(e=>e.type==='JOURNAL_MODE_STATE').at(-1).state.userId,B);});
test('permission granted late after account change never subscribes or starts old account',async()=>{const wait=deferred();const h=harness({permission:'default',permissionRequest:()=>wait.promise});await h.init();const start=h.start();await flush();h.context.userId=B;h.mode.contextChanged();await h.mode.restore();wait.resolve('granted');await start;await h.mode.whenIdle();assert(!h.calls.some(c=>c.name==='journal_mode_start'));assert(!h.events.some(e=>e.type==='SUBSCRIBE'));});
test('subscription completing after logout is destroyed and cannot become B subscription',async()=>{const wait=deferred();let createSub;const h=harness({subscribe:make=>{createSub=make;return wait.promise;}});await h.init();const start=h.start();while(!createSub)await flush();const logout=h.mode.beforeLogout();h.context.userId=B;h.mode.contextChanged();await h.mode.restore();wait.resolve(createSub());await Promise.all([start,logout]);await h.mode.whenIdle();assert(h.events.some(e=>e.type==='UNSUBSCRIBE'));assert(!h.calls.some(c=>c.name==='journal_mode_start'));assert.equal(h.mode.state().userId,B);});
test('late start response after logout does not recreate local session',async()=>{const wait=deferred();const h=harness({rpc:({name})=>name==='journal_mode_start'?wait.promise:undefined});await h.init();const task=h.start();while(!h.calls.some(c=>c.name==='journal_mode_start'))await flush();const logout=h.mode.beforeLogout();h.context.userId=null;h.context.ready=false;wait.resolve({data:{server_now:new Date(BASE).toISOString(),session:h.makeSession(A)}});await Promise.all([task,logout]);assert.equal(h.mode.state().session,null);assert.equal(h.mode.active(),false);});
test('worker persistence denial disables subscription instead of announcing active push',async()=>{const h=harness({ack:false});await h.init();await h.start();assert(h.events.some(e=>e.type==='UNSUBSCRIBE'));assert.equal(h.mode.state().session.push_enabled,false);assert(!h.toasts.some(t=>t.text.startsWith('Mode chantier activé')));});
test('presence is true only on focused visible exact feed, false in another tab',async()=>{const h=harness();await h.init();await h.start();h.mode.presence();await h.mode.whenIdle();assert.equal(h.calls.filter(c=>c.name==='journal_mode_presence').at(-1).args.p_visible,true);h.context.tab='actions';h.mode.presence();assert.equal(h.calls.filter(c=>c.name==='journal_mode_presence').at(-1).args.p_visible,false);h.context.tab='chat';h.setFocused(false);h.mode.presence();assert.equal(h.calls.filter(c=>c.name==='journal_mode_presence').at(-1).args.p_visible,false);});
test('wake lock released on hide and stop; deep link uses adapter without reload',async()=>{const h=harness();await h.init();await h.start();await h.mode.openFeed();h.mode.setWake(true);await flush();assert(h.events.some(e=>e.type==='WAKE'));h.doc.visibilityState='hidden';h.docEvents.visibilitychange();await flush();assert(h.events.some(e=>e.type==='RELEASE'));let ack;h.swEvents.message({data:{type:'JOURNAL_MODE_OPEN',chantierId:SITE,actionId:ID},ports:[{postMessage:value=>ack=value}]});assert.deepEqual(ack,{ok:true});await flush();assert(h.events.some(e=>e.type==='NAVIGATE'&&e.item.actionId===ID));await h.mode.control('stop');assert.equal(h.mode.state().wakeRequested,false);});
test('insecure old browser disables only mode extension and keeps app callable',()=>{const mode=create({getContext:()=>({}),toast(){}},{window:{},wallNow:()=>BASE,monoNow:()=>0});assert.doesNotThrow(()=>mode.contextChanged());assert.equal(mode.active(),false);});

 test('restore does not claim push is enabled when browser has no subscription',async()=>{const h=harness();h.sessions.set(A,h.makeSession(A));await h.init();assert.equal(h.mode.state().session.push_enabled,false);});
 test('notification click waits until form closes and acknowledges without navigation',async()=>{const h=harness();let overlay=true;h.adapter.isOverlayOpen=()=>overlay;await h.init();let ack;h.swEvents.message({data:{type:'JOURNAL_MODE_OPEN',chantierId:SITE,actionId:ID},ports:[{postMessage:value=>ack=value}]});assert.deepEqual(ack,{ok:true});await flush();assert(!h.events.some(e=>e.type==='NAVIGATE'));overlay=false;h.mode.tick();await flush();assert(h.events.some(e=>e.type==='NAVIGATE'));});

test('failed worker, unsubscribe and offline stop never claim silence or leave controls stuck',async()=>{let offline=false;const h=harness({offline:()=>offline,unsubscribe:()=>Promise.reject(Error('offline unsubscribe'))});await h.init();await h.start();offline=true;h.setAck(false);await h.mode.control('stop');assert.equal(h.mode.state().busy,false);assert(h.mode.state().pending);assert(h.toasts.some(t=>t.text.startsWith('Arrêt des alertes non confirmé')));assert(h.calls.some(c=>c.name==='journal_mode_control'));});
test('failed explicit restart cannot discard a persisted offline stop',async()=>{let rejectStart=false;const h=harness({offline:()=>true,rpc:({name})=>name==='journal_mode_start'&&rejectStart?{error:Error('restart failed')}:undefined});await h.init();await h.start();await h.mode.control('stop');rejectStart=true;await assert.rejects(h.start(),/restart failed/);assert.equal(h.mode.state().pending.operation,'stop');assert([...h.storage.keys()].some(k=>k.startsWith('journal_mode_intent_v1')));});
