BEGIN;
-- V15.6: permanent deletion, independent night generations and source-backed choices.
-- No user record is deleted when this migration is installed.
do $$ begin
 if to_regprocedure('journal_cr_private.api_v155(text,jsonb)') is null then
  alter function public.journal_cr_api(text,jsonb) set schema journal_cr_private;
  alter function journal_cr_private.journal_cr_api(text,jsonb) rename to api_v155;
 end if;
end $$;
create table if not exists journal_cr_private.night_resets (
 chantier_id uuid references public.chantiers(id) on delete cascade,
 night date not null, reset_at timestamptz not null, primary key(chantier_id,night)
);
-- Only a cutoff, never a restorable report or answers. It prevents old production reuse.
create table if not exists journal_cr_private.references_v156 (
 id text primary key, section_key text not null check(section_key in ('itc','catenaire')),
 type text not null check(type in ('SEL','Secteur','ZEP')), label text not null,
 reference text not null, sector text not null default '', sites jsonb not null, sources jsonb not null
);
insert into journal_cr_private.references_v156 values('24be983b89ac25ba760584e3','catenaire','SEL','1bis + 3bis + 5bis + 11bis du Sr MONTEREAU CHAMPIGNY SUR YONNE V1H 1bis','1bis + 3bis + 5bis + 11bis du Sr MONTEREAU CHAMPIGNY SUR YONNE V1H 1bis','Sr MONTEREAU CHAMPIGNY SUR YONNE V1H 1bis','["Montereau"]','[{"sheet": "S27 AINM", "row": 8, "cell": "W8"}, {"sheet": "S28 AINM", "row": 8, "cell": "W8"}, {"sheet": "WE S38-39 AINM", "row": 5, "cell": "W5"}, {"sheet": "S39 AINM", "row": 7, "cell": "W7"}, {"sheet": "WE S39-40 AINM", "row": 5, "cell": "W5"}, {"sheet": "S40 AINM", "row": 6, "cell": "W6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('201e7c36937b3d19ae4b38bc','catenaire','SEL','SEL 1 + 3 du Sr Montereau-Champigny sur Yonne voie 1M-1','1 + 3 du Sr Montereau-Champigny sur Yonne voie 1M-1','Sr Montereau-Champigny sur Yonne voie 1M-1','["Montereau"]','[{"sheet": "S19 AINM", "row": 6, "cell": "W6"}, {"sheet": "S20 AINM", "row": 6, "cell": "W6"}, {"sheet": "S21 AINM", "row": 6, "cell": "W6"}, {"sheet": "S22 AINM", "row": 6, "cell": "W6"}, {"sheet": "S23 AINM", "row": 6, "cell": "W6"}, {"sheet": "S24 AINM", "row": 6, "cell": "W6"}, {"sheet": "S25 AINM", "row": 6, "cell": "W6"}, {"sheet": "S26 AINM", "row": 6, "cell": "W6"}, {"sheet": "S32 AINM", "row": 9, "cell": "W9"}, {"sheet": "S37 AINM", "row": 9, "cell": "W9"}, {"sheet": "WE S38-39 AINM", "row": 5, "cell": "W5"}, {"sheet": "WE S39-40 AINM", "row": 5, "cell": "W5"}, {"sheet": "WE S39-40 AINM", "row": 9, "cell": "W9"}, {"sheet": "S41 AINM", "row": 10, "cell": "W10"}, {"sheet": "S42 AINM", "row": 11, "cell": "W11"}, {"sheet": "S43 AINM", "row": 10, "cell": "W10"}, {"sheet": "S45 AINM", "row": 9, "cell": "W9"}, {"sheet": "S46 AINM", "row": 9, "cell": "W9"}, {"sheet": "S47 AINM", "row": 9, "cell": "W9"}, {"sheet": "S48 AINM", "row": 9, "cell": "W9"}, {"sheet": "S49 AINM", "row": 9, "cell": "W9"}, {"sheet": "S50 AINM", "row": 9, "cell": "W9"}, {"sheet": "S51 AINM", "row": 9, "cell": "W9"}, {"sheet": "S52 AINM", "row": 9, "cell": "W9"}, {"sheet": "S44 AINM", "row": 9, "cell": "W9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('621cd5cd853fe443f7e58b9e','catenaire','SEL','Sél 12H du Sr Samoreau-Montereau V2','12H du Sr Samoreau-Montereau V2','Sr Samoreau-Montereau V2','["Montereau"]','[{"sheet": "S41 AINM", "row": 10, "cell": "W10"}, {"sheet": "S42 AINM", "row": 11, "cell": "W11"}, {"sheet": "S43 AINM", "row": 10, "cell": "W10"}, {"sheet": "S44 AINM", "row": 9, "cell": "W9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('8a0a953e91ea40f20ee0ee5f','catenaire','SEL','SEL 12H Sr Samoreau-Montereau V2','12H Sr Samoreau-Montereau V2','Sr Samoreau-Montereau V2','["Montereau"]','[{"sheet": "S16 AINM", "row": 6, "cell": "W6"}, {"sheet": "S17 AINM", "row": 6, "cell": "W6"}, {"sheet": "S18 AINM", "row": 6, "cell": "W6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('14214554f818a1c8c20412c1','catenaire','SEL','SEL 1Bis + 3Bis +11Bis du Sr Montereau-Champigny sur Yonne voie 1H-1Bis','1Bis + 3Bis +11Bis du Sr Montereau-Champigny sur Yonne voie 1H-1Bis','Sr Montereau-Champigny sur Yonne voie 1H-1Bis','["Montereau"]','[{"sheet": "S16 AINM", "row": 6, "cell": "W6"}, {"sheet": "S17 AINM", "row": 6, "cell": "W6"}, {"sheet": "S18 AINM", "row": 6, "cell": "W6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('b14d905efb86d5fde9f3f342','catenaire','SEL','SEL 2 +4 Sr Montereau-Champigny sur Yonne voie 2','2 +4 Sr Montereau-Champigny sur Yonne voie 2','Sr Montereau-Champigny sur Yonne voie 2','["Montereau"]','[{"sheet": "S19 AINM", "row": 6, "cell": "W6"}, {"sheet": "S20 AINM", "row": 6, "cell": "W6"}, {"sheet": "S21 AINM", "row": 6, "cell": "W6"}, {"sheet": "S22 AINM", "row": 6, "cell": "W6"}, {"sheet": "S23 AINM", "row": 6, "cell": "W6"}, {"sheet": "S24 AINM", "row": 6, "cell": "W6"}, {"sheet": "S25 AINM", "row": 6, "cell": "W6"}, {"sheet": "S26 AINM", "row": 6, "cell": "W6"}, {"sheet": "S32 AINM", "row": 9, "cell": "W9"}, {"sheet": "S37 AINM", "row": 9, "cell": "W9"}, {"sheet": "WE S38-39 AINM", "row": 5, "cell": "W5"}, {"sheet": "WE S39-40 AINM", "row": 5, "cell": "W5"}, {"sheet": "WE S39-40 AINM", "row": 9, "cell": "W9"}, {"sheet": "S41 AINM", "row": 10, "cell": "W10"}, {"sheet": "S42 AINM", "row": 11, "cell": "W11"}, {"sheet": "S43 AINM", "row": 10, "cell": "W10"}, {"sheet": "S45 AINM", "row": 9, "cell": "W9"}, {"sheet": "S46 AINM", "row": 9, "cell": "W9"}, {"sheet": "S47 AINM", "row": 9, "cell": "W9"}, {"sheet": "S48 AINM", "row": 9, "cell": "W9"}, {"sheet": "S49 AINM", "row": 9, "cell": "W9"}, {"sheet": "S50 AINM", "row": 9, "cell": "W9"}, {"sheet": "S51 AINM", "row": 9, "cell": "W9"}, {"sheet": "S52 AINM", "row": 9, "cell": "W9"}, {"sheet": "S44 AINM", "row": 9, "cell": "W9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('5b2030da51d9e2a6720e7c48','catenaire','SEL','Sél 26+28 du Sr Saint Mammès-Montereau V2','26+28 du Sr Saint Mammès-Montereau V2','Sr Saint Mammès-Montereau V2','["Montereau"]','[{"sheet": "S41 AINM", "row": 10, "cell": "W10"}, {"sheet": "S42 AINM", "row": 11, "cell": "W11"}, {"sheet": "S43 AINM", "row": 10, "cell": "W10"}, {"sheet": "S44 AINM", "row": 9, "cell": "W9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('6f8fd7b30ed222b2a1d1c138','catenaire','SEL','Sél 27+29+161 du Sr Saint Mammès-Montereau V1','27+29+161 du Sr Saint Mammès-Montereau V1','Sr Saint Mammès-Montereau V1','["Montereau"]','[{"sheet": "S41 AINM", "row": 10, "cell": "W10"}, {"sheet": "S42 AINM", "row": 11, "cell": "W11"}, {"sheet": "S43 AINM", "row": 10, "cell": "W10"}, {"sheet": "S44 AINM", "row": 9, "cell": "W9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('e7ef6bb0b469c7af9b60344b','catenaire','SEL','Sél 2bis et 4bis du Sr Montereau-Champigny-S-Yonne','2bis et 4bis du Sr Montereau-Champigny-S-Yonne','Sr Montereau-Champigny-S-Yonne','["Montereau"]','[{"sheet": "S41 AINM", "row": 10, "cell": "W10"}, {"sheet": "S42 AINM", "row": 11, "cell": "W11"}, {"sheet": "S43 AINM", "row": 10, "cell": "W10"}, {"sheet": "S44 AINM", "row": 9, "cell": "W9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('84d22b710a9a27214cb44e55','catenaire','SEL','SEL 2Bis Sr Montereau-Champigny sur Yonne voie 2H-2Bis','2Bis Sr Montereau-Champigny sur Yonne voie 2H-2Bis','Sr Montereau-Champigny sur Yonne voie 2H-2Bis','["Montereau"]','[{"sheet": "S16 AINM", "row": 6, "cell": "W6"}, {"sheet": "S17 AINM", "row": 6, "cell": "W6"}, {"sheet": "S18 AINM", "row": 6, "cell": "W6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('f74423fcad713c9bb75273f3','catenaire','SEL','SEL 7H +153 + 157 Sr Samoreau- Montereau','7H +153 + 157 Sr Samoreau- Montereau','Sr Samoreau- Montereau','["Montereau"]','[{"sheet": "S16 AINM", "row": 6, "cell": "W6"}, {"sheet": "S17 AINM", "row": 6, "cell": "W6"}, {"sheet": "S18 AINM", "row": 6, "cell": "W6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('4e626d23109d2164c2b4727e','catenaire','SEL','SEL 7H Secteur Samoreau-Montereau V1H','7H Secteur Samoreau-Montereau V1H','Secteur Samoreau-Montereau V1H','["Montereau"]','[{"sheet": "S41 AINM", "row": 10, "cell": "W10"}, {"sheet": "S42 AINM", "row": 11, "cell": "W11"}, {"sheet": "S43 AINM", "row": 10, "cell": "W10"}, {"sheet": "S44 AINM", "row": 9, "cell": "W9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('548f3d039d4698097cbd0f39','catenaire','Secteur','Dordives - GRIPOY voie 1','Dordives - GRIPOY voie 1','','["Moret Montargis"]','[{"sheet": "S42 AINM", "row": 8, "cell": "W8"}, {"sheet": "S43 AINM", "row": 8, "cell": "W8"}, {"sheet": "S44 AINM", "row": 8, "cell": "W8"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('d579afb7b68834a784ff424e','catenaire','Secteur','Feeder 7H Secteur Samoreau-Montereau V1H','Feeder 7H Secteur Samoreau-Montereau V1H','','["Montereau"]','[{"sheet": "S41 AINM", "row": 10, "cell": "W10"}, {"sheet": "S42 AINM", "row": 11, "cell": "W11"}, {"sheet": "S43 AINM", "row": 10, "cell": "W10"}, {"sheet": "S44 AINM", "row": 9, "cell": "W9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('9a97c0d9f33e3faff03e33c3','catenaire','Secteur','GRIPOY - Dordives voie 2','GRIPOY - Dordives voie 2','','["Moret Montargis"]','[{"sheet": "S42 AINM", "row": 8, "cell": "W8"}, {"sheet": "S43 AINM", "row": 8, "cell": "W8"}, {"sheet": "S44 AINM", "row": 8, "cell": "W8"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('42d6c00d91ece0962a7fdcaf','catenaire','Secteur','Groupe 103 (Sr Melun- samois V1+SR Samois - St Mammes V1)','Groupe 103 (Sr Melun- samois V1+SR Samois - St Mammes V1)','','["Melun Moret", "Moret Montargis"]','[{"sheet": "S37 AINM", "row": 5, "cell": "W5"}, {"sheet": "S38 AINM", "row": 5, "cell": "W5"}, {"sheet": "S41 AINM", "row": 5, "cell": "W5"}, {"sheet": "S42 AINM", "row": 5, "cell": "W5"}, {"sheet": "S43 AINM", "row": 5, "cell": "W5"}, {"sheet": "S44 AINM", "row": 5, "cell": "W5"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('ebec2225b631120327421c23','catenaire','Secteur','Groupe 104 (Sr Melun- samois V2+SR Samois - St Mammes V2)','Groupe 104 (Sr Melun- samois V2+SR Samois - St Mammes V2)','','["Melun Moret", "Montargis", "Moret Montargis"]','[{"sheet": "S37 AINM", "row": 5, "cell": "W5"}, {"sheet": "S37 AINM", "row": 7, "cell": "W7"}, {"sheet": "S38 AINM", "row": 5, "cell": "W5"}, {"sheet": "S41 AINM", "row": 5, "cell": "W5"}, {"sheet": "S42 AINM", "row": 5, "cell": "W5"}, {"sheet": "S43 AINM", "row": 5, "cell": "W5"}, {"sheet": "S44 AINM", "row": 5, "cell": "W5"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('2a0d3c429252209acf6e39e7','catenaire','Secteur','Sr Dordives -Gripoy voie 1','Sr Dordives -Gripoy voie 1','','["Montargis", "Moret Montargis"]','[{"sheet": "S27 AINM", "row": 7, "cell": "W7"}, {"sheet": "S28 AINM", "row": 7, "cell": "W7"}, {"sheet": "S29 AINM", "row": 6, "cell": "W6"}, {"sheet": "S30 AINM", "row": 6, "cell": "W6"}, {"sheet": "S31 AINM", "row": 6, "cell": "W6"}, {"sheet": "S32 AINM", "row": 5, "cell": "W5"}, {"sheet": "S32 AINM", "row": 7, "cell": "W7"}, {"sheet": "WE S39-40 AINM", "row": 7, "cell": "W7"}, {"sheet": "S45 AINM", "row": 5, "cell": "W5"}, {"sheet": "S45 AINM", "row": 7, "cell": "W7"}, {"sheet": "S46 AINM", "row": 5, "cell": "W5"}, {"sheet": "S46 AINM", "row": 7, "cell": "W7"}, {"sheet": "S47 AINM", "row": 5, "cell": "W5"}, {"sheet": "S47 AINM", "row": 7, "cell": "W7"}, {"sheet": "S48 AINM", "row": 5, "cell": "W5"}, {"sheet": "S48 AINM", "row": 7, "cell": "W7"}, {"sheet": "S49 AINM", "row": 5, "cell": "W5"}, {"sheet": "S49 AINM", "row": 7, "cell": "W7"}, {"sheet": "S50 AINM", "row": 5, "cell": "W5"}, {"sheet": "S50 AINM", "row": 7, "cell": "W7"}, {"sheet": "S51 AINM", "row": 5, "cell": "W5"}, {"sheet": "S51 AINM", "row": 7, "cell": "W7"}, {"sheet": "S52 AINM", "row": 5, "cell": "W5"}, {"sheet": "S52 AINM", "row": 7, "cell": "W7"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('aab9a7dc483bf7b60e2e319d','catenaire','Secteur','Sr Dordives -Gripoy voie 2','Sr Dordives -Gripoy voie 2','','["Montargis", "Moret Montargis"]','[{"sheet": "S27 AINM", "row": 7, "cell": "W7"}, {"sheet": "S28 AINM", "row": 7, "cell": "W7"}, {"sheet": "S29 AINM", "row": 6, "cell": "W6"}, {"sheet": "S30 AINM", "row": 6, "cell": "W6"}, {"sheet": "S31 AINM", "row": 6, "cell": "W6"}, {"sheet": "S32 AINM", "row": 5, "cell": "W5"}, {"sheet": "S32 AINM", "row": 7, "cell": "W7"}, {"sheet": "WE S39-40 AINM", "row": 7, "cell": "W7"}, {"sheet": "S45 AINM", "row": 5, "cell": "W5"}, {"sheet": "S45 AINM", "row": 7, "cell": "W7"}, {"sheet": "S46 AINM", "row": 5, "cell": "W5"}, {"sheet": "S46 AINM", "row": 7, "cell": "W7"}, {"sheet": "S47 AINM", "row": 5, "cell": "W5"}, {"sheet": "S47 AINM", "row": 7, "cell": "W7"}, {"sheet": "S48 AINM", "row": 5, "cell": "W5"}, {"sheet": "S48 AINM", "row": 7, "cell": "W7"}, {"sheet": "S49 AINM", "row": 5, "cell": "W5"}, {"sheet": "S49 AINM", "row": 7, "cell": "W7"}, {"sheet": "S50 AINM", "row": 5, "cell": "W5"}, {"sheet": "S50 AINM", "row": 7, "cell": "W7"}, {"sheet": "S51 AINM", "row": 5, "cell": "W5"}, {"sheet": "S51 AINM", "row": 7, "cell": "W7"}, {"sheet": "S52 AINM", "row": 5, "cell": "W5"}, {"sheet": "S52 AINM", "row": 7, "cell": "W7"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('96a4b62b58e8ee4a7741ac5a','catenaire','Secteur','Sr Les Larris - Dordives voie 1','Sr Les Larris - Dordives voie 1','','["Moret Montargis"]','[{"sheet": "S27 AINM", "row": 5, "cell": "W5"}, {"sheet": "S28 AINM", "row": 5, "cell": "W5"}, {"sheet": "S29 AINM", "row": 5, "cell": "W5"}, {"sheet": "S30 AINM", "row": 5, "cell": "W5"}, {"sheet": "S31 AINM", "row": 5, "cell": "W5"}, {"sheet": "S32 AINM", "row": 5, "cell": "W5"}, {"sheet": "S32 AINM", "row": 8, "cell": "W8"}, {"sheet": "S37 AINM", "row": 8, "cell": "W8"}, {"sheet": "WE S39-40 AINM", "row": 8, "cell": "W8"}, {"sheet": "S41 AINM", "row": 9, "cell": "W9"}, {"sheet": "S42 AINM", "row": 10, "cell": "W10"}, {"sheet": "S43 AINM", "row": 9, "cell": "W9"}, {"sheet": "S45 AINM", "row": 5, "cell": "W5"}, {"sheet": "S45 AINM", "row": 8, "cell": "W8"}, {"sheet": "S46 AINM", "row": 5, "cell": "W5"}, {"sheet": "S46 AINM", "row": 8, "cell": "W8"}, {"sheet": "S47 AINM", "row": 5, "cell": "W5"}, {"sheet": "S47 AINM", "row": 8, "cell": "W8"}, {"sheet": "S48 AINM", "row": 5, "cell": "W5"}, {"sheet": "S48 AINM", "row": 8, "cell": "W8"}, {"sheet": "S49 AINM", "row": 5, "cell": "W5"}, {"sheet": "S49 AINM", "row": 8, "cell": "W8"}, {"sheet": "S50 AINM", "row": 5, "cell": "W5"}, {"sheet": "S50 AINM", "row": 8, "cell": "W8"}, {"sheet": "S51 AINM", "row": 5, "cell": "W5"}, {"sheet": "S51 AINM", "row": 8, "cell": "W8"}, {"sheet": "S52 AINM", "row": 5, "cell": "W5"}, {"sheet": "S52 AINM", "row": 8, "cell": "W8"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('9de455ba806c093f18ddeee0','catenaire','Secteur','Sr Les Larris - Dordives voie 2','Sr Les Larris - Dordives voie 2','','["Moret Montargis"]','[{"sheet": "S27 AINM", "row": 5, "cell": "W5"}, {"sheet": "S28 AINM", "row": 5, "cell": "W5"}, {"sheet": "S29 AINM", "row": 5, "cell": "W5"}, {"sheet": "S30 AINM", "row": 5, "cell": "W5"}, {"sheet": "S31 AINM", "row": 5, "cell": "W5"}, {"sheet": "S32 AINM", "row": 5, "cell": "W5"}, {"sheet": "S32 AINM", "row": 8, "cell": "W8"}, {"sheet": "S37 AINM", "row": 8, "cell": "W8"}, {"sheet": "WE S39-40 AINM", "row": 8, "cell": "W8"}, {"sheet": "S41 AINM", "row": 9, "cell": "W9"}, {"sheet": "S42 AINM", "row": 10, "cell": "W10"}, {"sheet": "S43 AINM", "row": 9, "cell": "W9"}, {"sheet": "S45 AINM", "row": 5, "cell": "W5"}, {"sheet": "S45 AINM", "row": 8, "cell": "W8"}, {"sheet": "S46 AINM", "row": 5, "cell": "W5"}, {"sheet": "S46 AINM", "row": 8, "cell": "W8"}, {"sheet": "S47 AINM", "row": 5, "cell": "W5"}, {"sheet": "S47 AINM", "row": 8, "cell": "W8"}, {"sheet": "S48 AINM", "row": 5, "cell": "W5"}, {"sheet": "S48 AINM", "row": 8, "cell": "W8"}, {"sheet": "S49 AINM", "row": 5, "cell": "W5"}, {"sheet": "S49 AINM", "row": 8, "cell": "W8"}, {"sheet": "S50 AINM", "row": 5, "cell": "W5"}, {"sheet": "S50 AINM", "row": 8, "cell": "W8"}, {"sheet": "S51 AINM", "row": 5, "cell": "W5"}, {"sheet": "S51 AINM", "row": 8, "cell": "W8"}, {"sheet": "S52 AINM", "row": 5, "cell": "W5"}, {"sheet": "S52 AINM", "row": 8, "cell": "W8"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('a088f0a821d093f2b32e0be0','catenaire','Secteur','Sr Les Larris-Dordives voie 1','Sr Les Larris-Dordives voie 1','','["Moret Montargis"]','[{"sheet": "S16 AINM", "row": 5, "cell": "W5"}, {"sheet": "S17 AINM", "row": 5, "cell": "W5"}, {"sheet": "S18 AINM", "row": 5, "cell": "W5"}, {"sheet": "S19 AINM", "row": 5, "cell": "W5"}, {"sheet": "S20 AINM", "row": 5, "cell": "W5"}, {"sheet": "S21 AINM", "row": 5, "cell": "W5"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('07671658521a5940b5b426eb','catenaire','Secteur','Sr Les Larris-Dordives voie 2','Sr Les Larris-Dordives voie 2','','["Moret Montargis"]','[{"sheet": "S16 AINM", "row": 5, "cell": "W5"}, {"sheet": "S17 AINM", "row": 5, "cell": "W5"}, {"sheet": "S18 AINM", "row": 5, "cell": "W5"}, {"sheet": "S19 AINM", "row": 5, "cell": "W5"}, {"sheet": "S20 AINM", "row": 5, "cell": "W5"}, {"sheet": "S21 AINM", "row": 5, "cell": "W5"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('d31d50b08e30c1a2c13fbcb1','catenaire','Secteur','Sr MELUN SAMOREAU V1','Sr MELUN SAMOREAU V1','','["Montereau"]','[{"sheet": "S27 AINM", "row": 8, "cell": "W8"}, {"sheet": "S28 AINM", "row": 8, "cell": "W8"}, {"sheet": "WE S38-39 AINM", "row": 5, "cell": "W5"}, {"sheet": "S39 AINM", "row": 7, "cell": "W7"}, {"sheet": "WE S39-40 AINM", "row": 5, "cell": "W5"}, {"sheet": "S40 AINM", "row": 6, "cell": "W6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('4fe945fcc236438969a5a697','catenaire','Secteur','Sr MELUN SAMOREAU V2','Sr MELUN SAMOREAU V2','','["Montereau"]','[{"sheet": "S27 AINM", "row": 8, "cell": "W8"}, {"sheet": "S28 AINM", "row": 8, "cell": "W8"}, {"sheet": "WE S38-39 AINM", "row": 5, "cell": "W5"}, {"sheet": "S39 AINM", "row": 7, "cell": "W7"}, {"sheet": "WE S39-40 AINM", "row": 5, "cell": "W5"}, {"sheet": "S40 AINM", "row": 6, "cell": "W6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('2a9d8d3c194db79305bc6b39','catenaire','Secteur','Sr MONTEREAU CHAMPIGNY SUR YONNE V2H 2bis','Sr MONTEREAU CHAMPIGNY SUR YONNE V2H 2bis','','["Montereau"]','[{"sheet": "S27 AINM", "row": 8, "cell": "W8"}, {"sheet": "S28 AINM", "row": 8, "cell": "W8"}, {"sheet": "WE S38-39 AINM", "row": 5, "cell": "W5"}, {"sheet": "S39 AINM", "row": 7, "cell": "W7"}, {"sheet": "WE S39-40 AINM", "row": 5, "cell": "W5"}, {"sheet": "S40 AINM", "row": 6, "cell": "W6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('6b30f922fdfd5aca210b9f99','catenaire','Secteur','SR Montereau Voie de service','SR Montereau Voie de service','','["Montereau"]','[{"sheet": "S19 AINM", "row": 6, "cell": "W6"}, {"sheet": "S20 AINM", "row": 6, "cell": "W6"}, {"sheet": "S21 AINM", "row": 6, "cell": "W6"}, {"sheet": "S22 AINM", "row": 6, "cell": "W6"}, {"sheet": "S23 AINM", "row": 6, "cell": "W6"}, {"sheet": "S24 AINM", "row": 6, "cell": "W6"}, {"sheet": "S25 AINM", "row": 6, "cell": "W6"}, {"sheet": "S26 AINM", "row": 6, "cell": "W6"}, {"sheet": "S32 AINM", "row": 9, "cell": "W9"}, {"sheet": "S37 AINM", "row": 9, "cell": "W9"}, {"sheet": "WE S38-39 AINM", "row": 5, "cell": "W5"}, {"sheet": "WE S39-40 AINM", "row": 5, "cell": "W5"}, {"sheet": "WE S39-40 AINM", "row": 9, "cell": "W9"}, {"sheet": "S41 AINM", "row": 10, "cell": "W10"}, {"sheet": "S42 AINM", "row": 11, "cell": "W11"}, {"sheet": "S43 AINM", "row": 10, "cell": "W10"}, {"sheet": "S45 AINM", "row": 9, "cell": "W9"}, {"sheet": "S46 AINM", "row": 9, "cell": "W9"}, {"sheet": "S47 AINM", "row": 9, "cell": "W9"}, {"sheet": "S48 AINM", "row": 9, "cell": "W9"}, {"sheet": "S49 AINM", "row": 9, "cell": "W9"}, {"sheet": "S50 AINM", "row": 9, "cell": "W9"}, {"sheet": "S51 AINM", "row": 9, "cell": "W9"}, {"sheet": "S52 AINM", "row": 9, "cell": "W9"}, {"sheet": "S44 AINM", "row": 9, "cell": "W9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('2ceb8553fdec67bf39f3617d','catenaire','Secteur','Sr Moret-Les Larris voie 1','Sr Moret-Les Larris voie 1','','["Moret Montargis"]','[{"sheet": "S16 AINM", "row": 5, "cell": "W5"}, {"sheet": "S17 AINM", "row": 5, "cell": "W5"}, {"sheet": "S18 AINM", "row": 5, "cell": "W5"}, {"sheet": "S19 AINM", "row": 5, "cell": "W5"}, {"sheet": "S20 AINM", "row": 5, "cell": "W5"}, {"sheet": "S21 AINM", "row": 5, "cell": "W5"}, {"sheet": "S22 AINM", "row": 5, "cell": "W5"}, {"sheet": "S23 AINM", "row": 5, "cell": "W5"}, {"sheet": "S24 AINM", "row": 5, "cell": "W5"}, {"sheet": "S25 AINM", "row": 5, "cell": "W5"}, {"sheet": "S26 AINM", "row": 5, "cell": "W5"}, {"sheet": "S27 AINM", "row": 5, "cell": "W5"}, {"sheet": "S28 AINM", "row": 5, "cell": "W5"}, {"sheet": "S29 AINM", "row": 5, "cell": "W5"}, {"sheet": "S30 AINM", "row": 5, "cell": "W5"}, {"sheet": "S31 AINM", "row": 5, "cell": "W5"}, {"sheet": "S32 AINM", "row": 5, "cell": "W5"}, {"sheet": "S32 AINM", "row": 6, "cell": "W6"}, {"sheet": "WE S39-40 AINM", "row": 6, "cell": "W6"}, {"sheet": "S45 AINM", "row": 5, "cell": "W5"}, {"sheet": "S45 AINM", "row": 6, "cell": "W6"}, {"sheet": "S46 AINM", "row": 5, "cell": "W5"}, {"sheet": "S46 AINM", "row": 6, "cell": "W6"}, {"sheet": "S47 AINM", "row": 5, "cell": "W5"}, {"sheet": "S47 AINM", "row": 6, "cell": "W6"}, {"sheet": "S48 AINM", "row": 5, "cell": "W5"}, {"sheet": "S48 AINM", "row": 6, "cell": "W6"}, {"sheet": "S49 AINM", "row": 5, "cell": "W5"}, {"sheet": "S49 AINM", "row": 6, "cell": "W6"}, {"sheet": "S50 AINM", "row": 5, "cell": "W5"}, {"sheet": "S50 AINM", "row": 6, "cell": "W6"}, {"sheet": "S51 AINM", "row": 5, "cell": "W5"}, {"sheet": "S51 AINM", "row": 6, "cell": "W6"}, {"sheet": "S52 AINM", "row": 5, "cell": "W5"}, {"sheet": "S52 AINM", "row": 6, "cell": "W6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('453abacfe57edd8a7b6e2334','catenaire','Secteur','Sr Moret-Les Larris voie 2','Sr Moret-Les Larris voie 2','','["Moret Montargis"]','[{"sheet": "S16 AINM", "row": 5, "cell": "W5"}, {"sheet": "S17 AINM", "row": 5, "cell": "W5"}, {"sheet": "S18 AINM", "row": 5, "cell": "W5"}, {"sheet": "S19 AINM", "row": 5, "cell": "W5"}, {"sheet": "S20 AINM", "row": 5, "cell": "W5"}, {"sheet": "S21 AINM", "row": 5, "cell": "W5"}, {"sheet": "S22 AINM", "row": 5, "cell": "W5"}, {"sheet": "S23 AINM", "row": 5, "cell": "W5"}, {"sheet": "S24 AINM", "row": 5, "cell": "W5"}, {"sheet": "S25 AINM", "row": 5, "cell": "W5"}, {"sheet": "S26 AINM", "row": 5, "cell": "W5"}, {"sheet": "S27 AINM", "row": 5, "cell": "W5"}, {"sheet": "S28 AINM", "row": 5, "cell": "W5"}, {"sheet": "S29 AINM", "row": 5, "cell": "W5"}, {"sheet": "S30 AINM", "row": 5, "cell": "W5"}, {"sheet": "S31 AINM", "row": 5, "cell": "W5"}, {"sheet": "S32 AINM", "row": 5, "cell": "W5"}, {"sheet": "S32 AINM", "row": 6, "cell": "W6"}, {"sheet": "WE S39-40 AINM", "row": 6, "cell": "W6"}, {"sheet": "S45 AINM", "row": 5, "cell": "W5"}, {"sheet": "S45 AINM", "row": 6, "cell": "W6"}, {"sheet": "S46 AINM", "row": 5, "cell": "W5"}, {"sheet": "S46 AINM", "row": 6, "cell": "W6"}, {"sheet": "S47 AINM", "row": 5, "cell": "W5"}, {"sheet": "S47 AINM", "row": 6, "cell": "W6"}, {"sheet": "S48 AINM", "row": 5, "cell": "W5"}, {"sheet": "S48 AINM", "row": 6, "cell": "W6"}, {"sheet": "S49 AINM", "row": 5, "cell": "W5"}, {"sheet": "S49 AINM", "row": 6, "cell": "W6"}, {"sheet": "S50 AINM", "row": 5, "cell": "W5"}, {"sheet": "S50 AINM", "row": 6, "cell": "W6"}, {"sheet": "S51 AINM", "row": 5, "cell": "W5"}, {"sheet": "S51 AINM", "row": 6, "cell": "W6"}, {"sheet": "S52 AINM", "row": 5, "cell": "W5"}, {"sheet": "S52 AINM", "row": 6, "cell": "W6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('717ff6b0b6924395d2b6a9b4','catenaire','Secteur','SR St Mammes- Montereau V1','SR St Mammes- Montereau V1','','["Montereau"]','[{"sheet": "S19 AINM", "row": 6, "cell": "W6"}, {"sheet": "S20 AINM", "row": 6, "cell": "W6"}, {"sheet": "S21 AINM", "row": 6, "cell": "W6"}, {"sheet": "S22 AINM", "row": 6, "cell": "W6"}, {"sheet": "S23 AINM", "row": 6, "cell": "W6"}, {"sheet": "S24 AINM", "row": 6, "cell": "W6"}, {"sheet": "S25 AINM", "row": 6, "cell": "W6"}, {"sheet": "S26 AINM", "row": 6, "cell": "W6"}, {"sheet": "S32 AINM", "row": 9, "cell": "W9"}, {"sheet": "S37 AINM", "row": 9, "cell": "W9"}, {"sheet": "WE S38-39 AINM", "row": 5, "cell": "W5"}, {"sheet": "WE S39-40 AINM", "row": 5, "cell": "W5"}, {"sheet": "WE S39-40 AINM", "row": 9, "cell": "W9"}, {"sheet": "S45 AINM", "row": 9, "cell": "W9"}, {"sheet": "S46 AINM", "row": 9, "cell": "W9"}, {"sheet": "S47 AINM", "row": 9, "cell": "W9"}, {"sheet": "S48 AINM", "row": 9, "cell": "W9"}, {"sheet": "S49 AINM", "row": 9, "cell": "W9"}, {"sheet": "S50 AINM", "row": 9, "cell": "W9"}, {"sheet": "S51 AINM", "row": 9, "cell": "W9"}, {"sheet": "S52 AINM", "row": 9, "cell": "W9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('6f4752d96983c0b4528555d9','catenaire','Secteur','SR St Mammes- Montereau V2','SR St Mammes- Montereau V2','','["Montereau"]','[{"sheet": "S19 AINM", "row": 6, "cell": "W6"}, {"sheet": "S20 AINM", "row": 6, "cell": "W6"}, {"sheet": "S21 AINM", "row": 6, "cell": "W6"}, {"sheet": "S22 AINM", "row": 6, "cell": "W6"}, {"sheet": "S23 AINM", "row": 6, "cell": "W6"}, {"sheet": "S24 AINM", "row": 6, "cell": "W6"}, {"sheet": "S25 AINM", "row": 6, "cell": "W6"}, {"sheet": "S26 AINM", "row": 6, "cell": "W6"}, {"sheet": "S32 AINM", "row": 9, "cell": "W9"}, {"sheet": "S37 AINM", "row": 9, "cell": "W9"}, {"sheet": "WE S38-39 AINM", "row": 5, "cell": "W5"}, {"sheet": "WE S39-40 AINM", "row": 5, "cell": "W5"}, {"sheet": "WE S39-40 AINM", "row": 9, "cell": "W9"}, {"sheet": "S45 AINM", "row": 9, "cell": "W9"}, {"sheet": "S46 AINM", "row": 9, "cell": "W9"}, {"sheet": "S47 AINM", "row": 9, "cell": "W9"}, {"sheet": "S48 AINM", "row": 9, "cell": "W9"}, {"sheet": "S49 AINM", "row": 9, "cell": "W9"}, {"sheet": "S50 AINM", "row": 9, "cell": "W9"}, {"sheet": "S51 AINM", "row": 9, "cell": "W9"}, {"sheet": "S52 AINM", "row": 9, "cell": "W9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('a68b263a93beacf6a0aaaa79','itc','ZEP','GROUPE B de la gare de Montargis','GROUPE B de la gare de Montargis','','["Montargis LR"]','[{"sheet": "S37 AINM", "row": 11, "cell": "V11"}, {"sheet": "S38 AINM", "row": 7, "cell": "V7"}, {"sheet": "S39 AINM", "row": 6, "cell": "V6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('8d070b213c44303fd1052933','itc','ZEP','Groupe B Montereau PU','Groupe B Montereau PU','','["Montereau"]','[{"sheet": "S27 AINM", "row": 8, "cell": "V8"}, {"sheet": "S28 AINM", "row": 8, "cell": "V8"}, {"sheet": "WE S38-39 AINM", "row": 5, "cell": "V5"}, {"sheet": "S39 AINM", "row": 7, "cell": "V7"}, {"sheet": "WE S39-40 AINM", "row": 5, "cell": "V5"}, {"sheet": "S40 AINM", "row": 6, "cell": "V6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('e307387576175e464edf791e','itc','ZEP','Groupement ZEP 513 +515 +658','Groupement ZEP 513 +515 +658','','["Montereau"]','[{"sheet": "S41 AINM", "row": 10, "cell": "V10"}, {"sheet": "S42 AINM", "row": 11, "cell": "V11"}, {"sheet": "S43 AINM", "row": 10, "cell": "V10"}, {"sheet": "S44 AINM", "row": 9, "cell": "V9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('1bc3353e3f74554eb32c9206','itc','ZEP','Groupement ZEP 642+644+646+648','Groupement ZEP 642+644+646+648','','["Montereau"]','[{"sheet": "S41 AINM", "row": 10, "cell": "V10"}, {"sheet": "S42 AINM", "row": 11, "cell": "V11"}, {"sheet": "S43 AINM", "row": 10, "cell": "V10"}, {"sheet": "S44 AINM", "row": 9, "cell": "V9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('ffbf5232a431df0c6df4bcce','itc','ZEP','Groupement ZEP type G 513 + 515 + 658','Groupement ZEP type G 513 + 515 + 658','','["Montereau"]','[{"sheet": "S16 AINM", "row": 6, "cell": "V6"}, {"sheet": "S17 AINM", "row": 6, "cell": "V6"}, {"sheet": "S18 AINM", "row": 6, "cell": "V6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('a44c4a876611f505a16955e4','itc','ZEP','Groupement ZEP type G 644+646+648+658+662 Montereau PU','Groupement ZEP type G 644+646+648+658+662 Montereau PU','','["Montereau"]','[{"sheet": "S27 AINM", "row": 8, "cell": "V8"}, {"sheet": "S28 AINM", "row": 8, "cell": "V8"}, {"sheet": "WE S38-39 AINM", "row": 5, "cell": "V5"}, {"sheet": "S39 AINM", "row": 7, "cell": "V7"}, {"sheet": "WE S39-40 AINM", "row": 5, "cell": "V5"}, {"sheet": "S40 AINM", "row": 6, "cell": "V6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('99b3cea5c959476eaa97d4f0','itc','ZEP','Groupement ZEP Type G 648 + 646 + 644','Groupement ZEP Type G 648 + 646 + 644','','["Montereau"]','[{"sheet": "S16 AINM", "row": 6, "cell": "V6"}, {"sheet": "S17 AINM", "row": 6, "cell": "V6"}, {"sheet": "S18 AINM", "row": 6, "cell": "V6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('8a284874b6f59aeef794c3e1','itc','ZEP','Groupement ZEP type G 806+808+810+950','Groupement ZEP type G 806+808+810+950','','["Montereau"]','[{"sheet": "S19 AINM", "row": 6, "cell": "V6"}, {"sheet": "S20 AINM", "row": 6, "cell": "V6"}, {"sheet": "S21 AINM", "row": 6, "cell": "V6"}, {"sheet": "S22 AINM", "row": 6, "cell": "V6"}, {"sheet": "S23 AINM", "row": 6, "cell": "V6"}, {"sheet": "S24 AINM", "row": 6, "cell": "V6"}, {"sheet": "S25 AINM", "row": 6, "cell": "V6"}, {"sheet": "S26 AINM", "row": 6, "cell": "V6"}, {"sheet": "S32 AINM", "row": 9, "cell": "V9"}, {"sheet": "S37 AINM", "row": 9, "cell": "V9"}, {"sheet": "WE S38-39 AINM", "row": 5, "cell": "V5"}, {"sheet": "WE S39-40 AINM", "row": 5, "cell": "V5"}, {"sheet": "WE S39-40 AINM", "row": 9, "cell": "V9"}, {"sheet": "S41 AINM", "row": 10, "cell": "V10"}, {"sheet": "S42 AINM", "row": 11, "cell": "V11"}, {"sheet": "S43 AINM", "row": 10, "cell": "V10"}, {"sheet": "S45 AINM", "row": 9, "cell": "V9"}, {"sheet": "S46 AINM", "row": 9, "cell": "V9"}, {"sheet": "S47 AINM", "row": 9, "cell": "V9"}, {"sheet": "S48 AINM", "row": 9, "cell": "V9"}, {"sheet": "S49 AINM", "row": 9, "cell": "V9"}, {"sheet": "S50 AINM", "row": 9, "cell": "V9"}, {"sheet": "S51 AINM", "row": 9, "cell": "V9"}, {"sheet": "S52 AINM", "row": 9, "cell": "V9"}, {"sheet": "S44 AINM", "row": 9, "cell": "V9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('a14ae12328c736ce773eaac1','itc','ZEP','LR - MONTARGIS VOIE 2','LR - MONTARGIS VOIE 2','','["Montargis LR"]','[{"sheet": "S37 AINM", "row": 11, "cell": "V11"}, {"sheet": "S38 AINM", "row": 7, "cell": "V7"}, {"sheet": "S39 AINM", "row": 6, "cell": "V6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('077575b3fee26af98fb2cb66','itc','ZEP','MONTARGIS - LR VOIE 1','MONTARGIS - LR VOIE 1','','["Montargis LR"]','[{"sheet": "S37 AINM", "row": 11, "cell": "V11"}, {"sheet": "S38 AINM", "row": 7, "cell": "V7"}, {"sheet": "S39 AINM", "row": 6, "cell": "V6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('577b65ba2468ea0d8aaa57ca','itc','ZEP','ZEP 662','662','','["Montereau"]','[{"sheet": "S41 AINM", "row": 10, "cell": "V10"}, {"sheet": "S42 AINM", "row": 11, "cell": "V11"}, {"sheet": "S43 AINM", "row": 10, "cell": "V10"}, {"sheet": "S44 AINM", "row": 9, "cell": "V9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('c54ea2a52d59170483847116','itc','ZEP','ZEP 706','706','','["Melun Moret", "Moret Montargis"]','[{"sheet": "S37 AINM", "row": 5, "cell": "V5"}, {"sheet": "S38 AINM", "row": 5, "cell": "V5"}, {"sheet": "S41 AINM", "row": 5, "cell": "V5"}, {"sheet": "S42 AINM", "row": 5, "cell": "V5"}, {"sheet": "S43 AINM", "row": 5, "cell": "V5"}, {"sheet": "S44 AINM", "row": 5, "cell": "V5"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('215a382c0bf6b5207f7b1389','itc','ZEP','ZEP 707','707','','["Melun Moret", "Moret Montargis"]','[{"sheet": "S37 AINM", "row": 5, "cell": "V5"}, {"sheet": "S38 AINM", "row": 5, "cell": "V5"}, {"sheet": "S41 AINM", "row": 5, "cell": "V5"}, {"sheet": "S42 AINM", "row": 5, "cell": "V5"}, {"sheet": "S43 AINM", "row": 5, "cell": "V5"}, {"sheet": "S44 AINM", "row": 5, "cell": "V5"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('0d403a2bf9ac67e890e7dad1','itc','ZEP','ZEP de type G 230','de type G 230','','["Montargis"]','[{"sheet": "S27 AINM", "row": 7, "cell": "V7"}, {"sheet": "S28 AINM", "row": 7, "cell": "V7"}, {"sheet": "S29 AINM", "row": 6, "cell": "V6"}, {"sheet": "S30 AINM", "row": 6, "cell": "V6"}, {"sheet": "S31 AINM", "row": 6, "cell": "V6"}, {"sheet": "S32 AINM", "row": 7, "cell": "V7"}, {"sheet": "S37 AINM", "row": 7, "cell": "V7"}, {"sheet": "WE S39-40 AINM", "row": 7, "cell": "V7"}, {"sheet": "S45 AINM", "row": 7, "cell": "V7"}, {"sheet": "S46 AINM", "row": 7, "cell": "V7"}, {"sheet": "S47 AINM", "row": 7, "cell": "V7"}, {"sheet": "S48 AINM", "row": 7, "cell": "V7"}, {"sheet": "S49 AINM", "row": 7, "cell": "V7"}, {"sheet": "S50 AINM", "row": 7, "cell": "V7"}, {"sheet": "S51 AINM", "row": 7, "cell": "V7"}, {"sheet": "S52 AINM", "row": 7, "cell": "V7"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('a3581540fdc682cbb6931d12','itc','ZEP','ZEP de type G 602+604+606+607 (pose + dépose LTV)','de type G 602+604+606+607 (pose + dépose LTV)','','["Moret Montargis"]','[{"sheet": "S27 AINM", "row": 6, "cell": "V6"}, {"sheet": "S28 AINM", "row": 6, "cell": "V6"}, {"sheet": "S32 AINM", "row": 6, "cell": "V6"}, {"sheet": "S37 AINM", "row": 6, "cell": "V6"}, {"sheet": "WE S39-40 AINM", "row": 6, "cell": "V6"}, {"sheet": "S45 AINM", "row": 6, "cell": "V6"}, {"sheet": "S46 AINM", "row": 6, "cell": "V6"}, {"sheet": "S47 AINM", "row": 6, "cell": "V6"}, {"sheet": "S48 AINM", "row": 6, "cell": "V6"}, {"sheet": "S49 AINM", "row": 6, "cell": "V6"}, {"sheet": "S50 AINM", "row": 6, "cell": "V6"}, {"sheet": "S51 AINM", "row": 6, "cell": "V6"}, {"sheet": "S52 AINM", "row": 6, "cell": "V6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('8f647e48b9ecbcf4e5457725','itc','ZEP','ZEP de type G201+212+216','de type G201+212+216','','["Montargis"]','[{"sheet": "S27 AINM", "row": 7, "cell": "V7"}, {"sheet": "S28 AINM", "row": 7, "cell": "V7"}, {"sheet": "S29 AINM", "row": 6, "cell": "V6"}, {"sheet": "S30 AINM", "row": 6, "cell": "V6"}, {"sheet": "S31 AINM", "row": 6, "cell": "V6"}, {"sheet": "S32 AINM", "row": 7, "cell": "V7"}, {"sheet": "S37 AINM", "row": 7, "cell": "V7"}, {"sheet": "WE S39-40 AINM", "row": 7, "cell": "V7"}, {"sheet": "S45 AINM", "row": 7, "cell": "V7"}, {"sheet": "S46 AINM", "row": 7, "cell": "V7"}, {"sheet": "S47 AINM", "row": 7, "cell": "V7"}, {"sheet": "S48 AINM", "row": 7, "cell": "V7"}, {"sheet": "S49 AINM", "row": 7, "cell": "V7"}, {"sheet": "S50 AINM", "row": 7, "cell": "V7"}, {"sheet": "S51 AINM", "row": 7, "cell": "V7"}, {"sheet": "S52 AINM", "row": 7, "cell": "V7"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('ecd03c10768f8b5c6e6149bd','itc','ZEP','ZEP type G 662','type G 662','','["Montereau"]','[{"sheet": "S16 AINM", "row": 6, "cell": "V6"}, {"sheet": "S17 AINM", "row": 6, "cell": "V6"}, {"sheet": "S18 AINM", "row": 6, "cell": "V6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('32116329e23dc04da11a476c','itc','ZEP','ZEP type G 785','type G 785','','["Montereau"]','[{"sheet": "S19 AINM", "row": 6, "cell": "V6"}, {"sheet": "S20 AINM", "row": 6, "cell": "V6"}, {"sheet": "S21 AINM", "row": 6, "cell": "V6"}, {"sheet": "S22 AINM", "row": 6, "cell": "V6"}, {"sheet": "S23 AINM", "row": 6, "cell": "V6"}, {"sheet": "S24 AINM", "row": 6, "cell": "V6"}, {"sheet": "S25 AINM", "row": 6, "cell": "V6"}, {"sheet": "S26 AINM", "row": 6, "cell": "V6"}, {"sheet": "S32 AINM", "row": 9, "cell": "V9"}, {"sheet": "S37 AINM", "row": 9, "cell": "V9"}, {"sheet": "WE S38-39 AINM", "row": 5, "cell": "V5"}, {"sheet": "WE S39-40 AINM", "row": 5, "cell": "V5"}, {"sheet": "WE S39-40 AINM", "row": 9, "cell": "V9"}, {"sheet": "S41 AINM", "row": 10, "cell": "V10"}, {"sheet": "S42 AINM", "row": 11, "cell": "V11"}, {"sheet": "S43 AINM", "row": 10, "cell": "V10"}, {"sheet": "S45 AINM", "row": 9, "cell": "V9"}, {"sheet": "S46 AINM", "row": 9, "cell": "V9"}, {"sheet": "S47 AINM", "row": 9, "cell": "V9"}, {"sheet": "S48 AINM", "row": 9, "cell": "V9"}, {"sheet": "S49 AINM", "row": 9, "cell": "V9"}, {"sheet": "S50 AINM", "row": 9, "cell": "V9"}, {"sheet": "S51 AINM", "row": 9, "cell": "V9"}, {"sheet": "S52 AINM", "row": 9, "cell": "V9"}, {"sheet": "S44 AINM", "row": 9, "cell": "V9"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('80833ca3e5b79ab1b56ed111','itc','ZEP','ZEP type L MELUN-MORET V1','type L MELUN-MORET V1','','["Melun Moret"]','[{"sheet": "S41 AINM", "row": 6, "cell": "V6"}, {"sheet": "S42 AINM", "row": 6, "cell": "V6"}, {"sheet": "S43 AINM", "row": 6, "cell": "V6"}, {"sheet": "S44 AINM", "row": 6, "cell": "V6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('54b6ddf2d79177fd0b4b3e02','itc','ZEP','ZEP type L MONTARGIS-MORET V2','type L MONTARGIS-MORET V2','','["Moret Montargis"]','[{"sheet": "S16 AINM", "row": 5, "cell": "V5"}, {"sheet": "S17 AINM", "row": 5, "cell": "V5"}, {"sheet": "S18 AINM", "row": 5, "cell": "V5"}, {"sheet": "S19 AINM", "row": 5, "cell": "V5"}, {"sheet": "S20 AINM", "row": 5, "cell": "V5"}, {"sheet": "S21 AINM", "row": 5, "cell": "V5"}, {"sheet": "S22 AINM", "row": 5, "cell": "V5"}, {"sheet": "S23 AINM", "row": 5, "cell": "V5"}, {"sheet": "S24 AINM", "row": 5, "cell": "V5"}, {"sheet": "S25 AINM", "row": 5, "cell": "V5"}, {"sheet": "S26 AINM", "row": 5, "cell": "V5"}, {"sheet": "S27 AINM", "row": 5, "cell": "V5"}, {"sheet": "S28 AINM", "row": 5, "cell": "V5"}, {"sheet": "S29 AINM", "row": 5, "cell": "V5"}, {"sheet": "S30 AINM", "row": 5, "cell": "V5"}, {"sheet": "S32 AINM", "row": 5, "cell": "V5"}, {"sheet": "S32 AINM", "row": 6, "cell": "V6"}, {"sheet": "S32 AINM", "row": 8, "cell": "V8"}, {"sheet": "S37 AINM", "row": 6, "cell": "V6"}, {"sheet": "S37 AINM", "row": 8, "cell": "V8"}, {"sheet": "S37 AINM", "row": 10, "cell": "V10"}, {"sheet": "S38 AINM", "row": 6, "cell": "V6"}, {"sheet": "S39 AINM", "row": 5, "cell": "V5"}, {"sheet": "WE S39-40 AINM", "row": 6, "cell": "V6"}, {"sheet": "WE S39-40 AINM", "row": 8, "cell": "V8"}, {"sheet": "S40 AINM", "row": 5, "cell": "V5"}, {"sheet": "S41 AINM", "row": 8, "cell": "V8"}, {"sheet": "S41 AINM", "row": 9, "cell": "V9"}, {"sheet": "S42 AINM", "row": 8, "cell": "V8"}, {"sheet": "S43 AINM", "row": 7, "cell": "V7"}, {"sheet": "S45 AINM", "row": 5, "cell": "V5"}, {"sheet": "S45 AINM", "row": 6, "cell": "V6"}, {"sheet": "S45 AINM", "row": 8, "cell": "V8"}, {"sheet": "S46 AINM", "row": 5, "cell": "V5"}, {"sheet": "S46 AINM", "row": 6, "cell": "V6"}, {"sheet": "S46 AINM", "row": 8, "cell": "V8"}, {"sheet": "S47 AINM", "row": 5, "cell": "V5"}, {"sheet": "S47 AINM", "row": 6, "cell": "V6"}, {"sheet": "S47 AINM", "row": 8, "cell": "V8"}, {"sheet": "S48 AINM", "row": 5, "cell": "V5"}, {"sheet": "S48 AINM", "row": 6, "cell": "V6"}, {"sheet": "S48 AINM", "row": 8, "cell": "V8"}, {"sheet": "S49 AINM", "row": 5, "cell": "V5"}, {"sheet": "S49 AINM", "row": 6, "cell": "V6"}, {"sheet": "S49 AINM", "row": 8, "cell": "V8"}, {"sheet": "S50 AINM", "row": 5, "cell": "V5"}, {"sheet": "S50 AINM", "row": 6, "cell": "V6"}, {"sheet": "S50 AINM", "row": 8, "cell": "V8"}, {"sheet": "S51 AINM", "row": 5, "cell": "V5"}, {"sheet": "S51 AINM", "row": 6, "cell": "V6"}, {"sheet": "S51 AINM", "row": 8, "cell": "V8"}, {"sheet": "S52 AINM", "row": 5, "cell": "V5"}, {"sheet": "S52 AINM", "row": 6, "cell": "V6"}, {"sheet": "S52 AINM", "row": 8, "cell": "V8"}, {"sheet": "S44 AINM", "row": 7, "cell": "V7"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('b7432333adb4b3f60598a375','itc','ZEP','ZEP type L MORET-MELUN V2','type L MORET-MELUN V2','','["Melun Moret"]','[{"sheet": "S41 AINM", "row": 6, "cell": "V6"}, {"sheet": "S42 AINM", "row": 6, "cell": "V6"}, {"sheet": "S43 AINM", "row": 6, "cell": "V6"}, {"sheet": "S44 AINM", "row": 6, "cell": "V6"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;
insert into journal_cr_private.references_v156 values('7fa17c5ee75e14e0c8d7cba3','itc','ZEP','ZEP type L MORET-MONTARGIS V1','type L MORET-MONTARGIS V1','','["Moret Montargis"]','[{"sheet": "S16 AINM", "row": 5, "cell": "V5"}, {"sheet": "S17 AINM", "row": 5, "cell": "V5"}, {"sheet": "S18 AINM", "row": 5, "cell": "V5"}, {"sheet": "S19 AINM", "row": 5, "cell": "V5"}, {"sheet": "S20 AINM", "row": 5, "cell": "V5"}, {"sheet": "S21 AINM", "row": 5, "cell": "V5"}, {"sheet": "S22 AINM", "row": 5, "cell": "V5"}, {"sheet": "S23 AINM", "row": 5, "cell": "V5"}, {"sheet": "S24 AINM", "row": 5, "cell": "V5"}, {"sheet": "S25 AINM", "row": 5, "cell": "V5"}, {"sheet": "S26 AINM", "row": 5, "cell": "V5"}, {"sheet": "S27 AINM", "row": 5, "cell": "V5"}, {"sheet": "S28 AINM", "row": 5, "cell": "V5"}, {"sheet": "S29 AINM", "row": 5, "cell": "V5"}, {"sheet": "S30 AINM", "row": 5, "cell": "V5"}, {"sheet": "S32 AINM", "row": 5, "cell": "V5"}, {"sheet": "S32 AINM", "row": 6, "cell": "V6"}, {"sheet": "S32 AINM", "row": 8, "cell": "V8"}, {"sheet": "S37 AINM", "row": 6, "cell": "V6"}, {"sheet": "S37 AINM", "row": 8, "cell": "V8"}, {"sheet": "S37 AINM", "row": 10, "cell": "V10"}, {"sheet": "S38 AINM", "row": 6, "cell": "V6"}, {"sheet": "S39 AINM", "row": 5, "cell": "V5"}, {"sheet": "WE S39-40 AINM", "row": 6, "cell": "V6"}, {"sheet": "WE S39-40 AINM", "row": 8, "cell": "V8"}, {"sheet": "S40 AINM", "row": 5, "cell": "V5"}, {"sheet": "S41 AINM", "row": 8, "cell": "V8"}, {"sheet": "S41 AINM", "row": 9, "cell": "V9"}, {"sheet": "S42 AINM", "row": 8, "cell": "V8"}, {"sheet": "S43 AINM", "row": 7, "cell": "V7"}, {"sheet": "S45 AINM", "row": 5, "cell": "V5"}, {"sheet": "S45 AINM", "row": 6, "cell": "V6"}, {"sheet": "S45 AINM", "row": 8, "cell": "V8"}, {"sheet": "S46 AINM", "row": 5, "cell": "V5"}, {"sheet": "S46 AINM", "row": 6, "cell": "V6"}, {"sheet": "S46 AINM", "row": 8, "cell": "V8"}, {"sheet": "S47 AINM", "row": 5, "cell": "V5"}, {"sheet": "S47 AINM", "row": 6, "cell": "V6"}, {"sheet": "S47 AINM", "row": 8, "cell": "V8"}, {"sheet": "S48 AINM", "row": 5, "cell": "V5"}, {"sheet": "S48 AINM", "row": 6, "cell": "V6"}, {"sheet": "S48 AINM", "row": 8, "cell": "V8"}, {"sheet": "S49 AINM", "row": 5, "cell": "V5"}, {"sheet": "S49 AINM", "row": 6, "cell": "V6"}, {"sheet": "S49 AINM", "row": 8, "cell": "V8"}, {"sheet": "S50 AINM", "row": 5, "cell": "V5"}, {"sheet": "S50 AINM", "row": 6, "cell": "V6"}, {"sheet": "S50 AINM", "row": 8, "cell": "V8"}, {"sheet": "S51 AINM", "row": 5, "cell": "V5"}, {"sheet": "S51 AINM", "row": 6, "cell": "V6"}, {"sheet": "S51 AINM", "row": 8, "cell": "V8"}, {"sheet": "S52 AINM", "row": 5, "cell": "V5"}, {"sheet": "S52 AINM", "row": 6, "cell": "V6"}, {"sheet": "S52 AINM", "row": 8, "cell": "V8"}, {"sheet": "S44 AINM", "row": 7, "cell": "V7"}]') on conflict(id) do update set label=excluded.label,reference=excluded.reference,sector=excluded.sector,sites=excluded.sites,sources=excluded.sources;

create or replace function journal_cr_private.field_choices(p_id uuid,p_key text) returns jsonb language sql stable set search_path='' as $$
 select coalesce(jsonb_agg(to_jsonb(c)||jsonb_build_object('chantier',array_to_string(array(select jsonb_array_elements_text(c.sites)),', ')) order by c.type,c.label),'[]')
 from journal_cr_private.references_v156 c where c.section_key=p_key;
$$;
create or replace function journal_cr_private.erase_report_data() returns trigger language plpgsql security definer set search_path='' as $$
begin
 -- Cascaded chantier deletion needs no cutoff: the chantier itself disappears.
 if exists(select 1 from public.chantiers where id=old.chantier_id) then
  insert into journal_cr_private.night_resets values(old.chantier_id,old.night,clock_timestamp())
  on conflict(chantier_id,night) do update set reset_at=excluded.reset_at;
 end if;
 -- Old email envelopes contain copies outside the report FK graph. Remove the
 -- deleted report from these envelopes, retaining other reports' own snapshots.
 update journal_cr_private.deliveries set report_ids=array_remove(report_ids,old.id),
 snapshots=coalesce((select jsonb_agg(x) from jsonb_array_elements(snapshots) x where coalesce(x->>'id',x->>'report_id','')<>old.id::text),'[]'),
 body='',subject='CR off',recipients='[]',state=case when state='pending' then 'failed' else state end,error_code='report_permanently_deleted'
 where old.id=any(report_ids);
 delete from journal_cr_private.deliveries where cardinality(report_ids)=0;
 return old;
end $$;
drop trigger if exists cr_erase_data on journal_cr_private.reports;
create trigger cr_erase_data before delete on journal_cr_private.reports for each row execute function journal_cr_private.erase_report_data();
create or replace function journal_cr_private.sync_production(p_site uuid,p_night date) returns void language plpgsql security definer set search_path='' as $$
declare sheets jsonb;lines jsonb;complete boolean;
begin
 select coalesce(jsonb_agg(to_jsonb(p) order by p.created_at,p.id),'[]') into sheets from journal_cr_private.production_sheets p where chantier_id=p_site and night=p_night and p.created_at>coalesce((select reset_at from journal_cr_private.night_resets where chantier_id=p_site and night=p_night),'-infinity'::timestamptz);
 if jsonb_array_length(sheets)=0 then return;end if;
 select jsonb_agg(x),bool_and(x->>'progress' is not null) into lines,complete from jsonb_array_elements(sheets) s cross join lateral jsonb_array_elements(s->'items') x;
 update journal_cr_private.sections s set value=s.value||jsonb_build_object('production_sheets',sheets,'production_text',journal_cr_private.production_text(lines)),
 status=case when s.value->>'production_mode'='text' then case when length(trim(coalesce(s.value->>'body','')))>0 then 'complete' else 'a_renseigner' end when complete then 'complete' else 'en_cours' end,version=s.version+1
 from journal_cr_private.reports r where s.report_id=r.id and s.key='technique' and r.chantier_id=p_site and r.night=p_night and r.state='draft' and r.deleted_at is null
 and s.value->'production_sheets' is distinct from sheets;
 update journal_cr_private.field_requests request_row set base_version=section_row.version,
 draft=jsonb_set(request_row.draft,'{sheets}',sheets),version=request_row.version+1
 from journal_cr_private.sections section_row join journal_cr_private.reports report_row on report_row.id=section_row.report_id
 where request_row.report_id=report_row.id and request_row.section_key='technique' and section_row.key='technique'
 and report_row.chantier_id=p_site and report_row.night=p_night and report_row.deleted_at is null and report_row.state='draft'
 and request_row.state='open' and request_row.saved_at is null and request_row.base_version<>section_row.version;
end $$;
create or replace function public.journal_production_api(p_action text,p_payload jsonb default '{}') returns jsonb language plpgsql security definer set search_path='' as $$
declare sid uuid:=(p_payload->>'chantier_id')::uuid;d date:=(p_payload->>'night')::date;rid uuid;result jsonb;
begin
 if auth.uid() is null or not public.journal_v142_is_active() or not journal_cr_private.member(auth.uid(),sid) then raise exception 'Production inaccessible';end if;
 if p_action='save' then
  if not (public.journal_v142_can_write(sid) or journal_cr_private.can_fill_production(sid,d)) then raise exception 'Accès en écriture requis';end if;
  perform pg_advisory_xact_lock(hashtextextended(sid::text||d::text,0));
  if exists(select 1 from journal_cr_private.field_requests q join journal_cr_private.reports r on r.id=q.report_id where r.chantier_id=sid and r.night=d and r.deleted_at is null and q.section_key='technique' and q.state='submitted') and not journal_cr_private.manager(sid) then raise exception 'Informations transmises : demander une correction à l’administrateur';end if;
  if not exists(select 1 from journal_cr_private.night_resets z join journal_cr_private.production_sheets p on p.chantier_id=z.chantier_id and p.night=z.night
    where z.chantier_id=sid and z.night=d and p.id=(p_payload->>'id')::uuid and p.created_at<=z.reset_at) then
   rid:=journal_cr_private.ensure_report(sid,d,auth.uid());
  end if;
 end if;
 result:=journal_cr_private.production_api_v154(p_action,p_payload);
 return result;
end $$;

create or replace function public.journal_cr_api(p_action text,p_payload jsonb default '{}') returns jsonb language plpgsql security definer set search_path='' as $$
declare uid uuid:=auth.uid();ids uuid[];rid uuid;sid uuid;d date;r journal_cr_private.reports;result jsonb;
begin
 if uid is null or not public.journal_v142_is_active() then raise exception 'Connexion active requise';end if;
 if octet_length(p_payload::text)>300000 then raise exception 'Demande trop volumineuse';end if;
 if p_action='restore_reports' then raise exception 'La restauration est supprimée. Préparez un nouveau CR vierge.';
 elsif p_action='list' then
  if coalesce((p_payload->>'deleted')::boolean,false) then return '[]';end if;
  -- Previously soft-deleted documents can be explicitly erased, never restored.
  return journal_cr_private.api_v155('list',p_payload||'{"deleted":false}')||
   case when coalesce((p_payload->>'offset')::int,0)=0 then journal_cr_private.api_v155('list','{"deleted":true}') else '[]'::jsonb end;
 elsif p_action='delete_reports' then
  select array_agg(distinct v::uuid) into ids from jsonb_array_elements_text(p_payload->'ids') v;
  if coalesce(cardinality(ids),0) not between 1 and 200 then raise exception 'Sélectionner les CR concernés';end if;
  if exists(select 1 from journal_cr_private.reports where id=any(ids) and not (journal_cr_private.manager(chantier_id) and journal_cr_private.member(uid,chantier_id))) then raise exception 'Suppression réservée aux administrateurs des chantiers concernés';end if;
  -- Lock in the same order as submissions and creation; retries of an erased UUID are harmless.
  for r in select * from journal_cr_private.reports where id=any(ids) order by chantier_id,night loop
   perform pg_advisory_xact_lock(hashtextextended(r.chantier_id::text||r.night::text,0));
  end loop;
  delete from journal_cr_private.reports where id=any(ids) and journal_cr_private.manager(chantier_id) and journal_cr_private.member(uid,chantier_id);
  return '{"deleted":true}';
 elsif p_action='create' then
  sid:=(p_payload->>'chantier_id')::uuid;d:=(p_payload->>'night')::date;
  if not journal_cr_private.manager(sid) or not journal_cr_private.member(uid,sid) then raise exception 'Préparation réservée à l’administrateur du chantier';end if;
  if d is null or d not between current_date-366 and current_date+31 then raise exception 'Date de nuit invalide';end if;
  perform pg_advisory_xact_lock(hashtextextended(sid::text||d::text,0));
  -- An old soft removal cannot occupy this night or restore its former content.
  delete from journal_cr_private.reports where chantier_id=sid and night=d and deleted_at is not null;
  if exists(select 1 from journal_cr_private.night_resets where chantier_id=sid and night=d) then
   p_payload:=p_payload||'{"reuse":false}';
  end if;
 end if;
 return journal_cr_private.api_v155(p_action,p_payload);
end $$;
revoke all on all tables in schema journal_cr_private from public,anon,authenticated,service_role;
revoke all on all functions in schema journal_cr_private from public,anon,authenticated,service_role;
revoke all on function public.journal_cr_api(text,jsonb),public.journal_production_api(text,jsonb) from public,anon;
grant execute on function public.journal_cr_api(text,jsonb),public.journal_production_api(text,jsonb) to authenticated;
create or replace function public.journal_delete_site_v156(p_chantier_id uuid) returns void language plpgsql security definer set search_path='' as $$
begin
 if auth.uid() is null or not public.journal_v142_is_active() or not exists(select 1 from public.journal_administrators where user_id=auth.uid() and role='proprietaire') then raise exception 'Suppression du chantier réservée au propriétaire principal';end if;
 -- Reuse historical cleanup when installed, including legacy foreign keys.
 if to_regprocedure('public.delete_journal_chantier(uuid)') is not null then
  perform public.delete_journal_chantier(p_chantier_id);
 end if;
 -- These legacy tables do not consistently declare ON DELETE CASCADE.
 delete from public.chantier_read_states where chantier_id=p_chantier_id;
 delete from public.chantier_message_reactions where chantier_id=p_chantier_id;
 delete from public.chantier_attachments where chantier_id=p_chantier_id;
 delete from public.chantier_daily_logs where chantier_id=p_chantier_id;
 delete from public.chantier_risks where chantier_id=p_chantier_id;
 delete from public.chantier_invitations where chantier_id=p_chantier_id;
 delete from public.chantiers where id=p_chantier_id;
end $$;
revoke all on function public.journal_delete_site_v156(uuid) from public,anon,service_role;
grant execute on function public.journal_delete_site_v156(uuid) to authenticated;

create table if not exists journal_cr_private.writing_usage(user_id uuid,hour timestamptz,requests int not null,primary key(user_id,hour));
create or replace function public.journal_writing_access(p_site uuid,p_count boolean default true) returns boolean language plpgsql security definer set search_path='' as $$
declare n int;
begin
 if auth.uid() is null or not public.journal_v142_is_active() or not journal_cr_private.member(auth.uid(),p_site) then return false;end if;
 if not p_count then return true;end if;
 insert into journal_cr_private.writing_usage values(auth.uid(),date_trunc('hour',now()),1)
 on conflict(user_id,hour) do update set requests=journal_cr_private.writing_usage.requests+1 returning requests into n;
 delete from journal_cr_private.writing_usage where hour<now()-interval '2 days';return n<=30;
end $$;
revoke all on journal_cr_private.writing_usage from public,anon,authenticated,service_role;
revoke all on function public.journal_writing_access(uuid,boolean) from public,anon,service_role;
grant execute on function public.journal_writing_access(uuid,boolean) to authenticated;
NOTIFY pgrst,'reload schema';
COMMIT;
